### ISSUE TITLE
GWAS

### ISSUE THREAD

**Issue by irn-alex** [genetics-statistics/GEMMA#102]
I tried to fit a relationship matrix with 3 columns (id id value) for GWAS analysis in GEMMA but couldn't run the job. The GWAS analysis works fine without fitting GRM.

This is the command I used:

```
 ./gemma -bfile test -km 2 -k test.grm -lmm 1 -o test
```

The error message:

```
Start Eigen-Decomposition...
pve estimate =0
se(pve) =0
gsl: newton.c:74: ERROR: derivative is zero                     0.00%
Default GSL error handler invoked.
Aborted
```

Regards,
Alex

**Comment by pcarbo** [comment]
@irn-alex If you can provide your files `test` and `test.grm` somehow, I can take a look. It is hard to say what could be going wrong without looking at your relationship matrix. You could also try using the `-eigen` option to first compute the eigendecomposition of your matrix.

**Comment by irn-alex** [comment]
Thanks, I tested fitting the full relationship matrix (n*n) and it looks fine but not. I try -eigen option.

**Comment by pcarbo** [comment]
@irn-alex Okay, that is progress. If I remember correctly, you need to be careful that the ids match the "individual id" column in the PLINK file. I remember another user had an issue with this, but unfortunately I can't find the details now. Or if it is working with full relationship matrix, maybe continue with that approach.

**Comment by pjotrp** [comment]
@pcarbo, for anyone who files an issue it would be useful to ask for the log file and platform so we can see what version of GEMMA is running and making data available so we can reproduce the error. I would like to collect these errors and make sure GEMMA reports correctly.

**Comment by pcarbo** [comment]
@pjotrp Agreed!

**Comment by irn-alex** [comment]
I used the linux executable version I downloaded this week from : http://www.xzlab.org/software.html. GEMMA Version = 0.96
I just changed the mode by: chmod 755. The main point was that a (nx3) kinship matrix was not working in GWAS but the full matrix (nxn) did worked.Also it looks like gemma doesn't give me the log file! when there is an error. I got the log file when I fitted the full kinship matrix. 

Cheers,Alex

**Comment by pcarbo** [comment]
@pjotrp Do you think this might be fixed in the new release? Perhaps we should add a test for loading kinship matrices stored in this way.

**Comment by pjotrp** [comment]
I think the kinship should be symmetric. @xiangzhou ?

**Comment by pjotrp** [comment]
Please continue on the mailing list: https://groups.google.com/forum/#!forum/gemma-discussion

**Comment by pcarbo** [comment]
@pjotrp The n x 3 relatedness format is also allowed; please see p. 13 of the manual. A couple of people have encountered issues with this format, but I'm not certain it is a bug or an issue with their input files.

**Comment by pcarbo** [comment]
@irn-alex  To clarify, we are migrating all Q&A and discussion (except for bug reports and development-related discussion) to the GEMMA mailing list. I encourage you to subscribe to the mailing list and followup on your issue there. Please see:

https://groups.google.com/group/gemma-discussion

(Note it is easy to unsubcribe at any point.)
