### ISSUE TITLE
Segmentation fault: 11 when pheno file has extraneous column

### ISSUE THREAD

**Issue by angelaparodymerino** [genetics-statistics/GEMMA#105]
Hi,

I managed to create the bimbam.gen file which looks fine. However, I tested it in GEMMA:

gemma -g bimbam.gen -p pheno.txt -bslmm 1 -o out

and I get:

Reading Files ... 
Segmentation fault: 11

I suspect it has to do with the format of the bimbam.gen file, but I opened it and it looks fine. Any idea of what it might be happening?

Thanks,

Ángela

**Comment by pcarbo** [comment]
> I suspect it has to do with the format of the `bimbam.gen` file. 

@angelaparodymerino Yes, that is most likely the explanation. Can you share the first few lines of the genotype and phenotype files?

**Comment by angelaparodymerino** [comment]
Thanks for your quick replies!

I was going to share my files but I found out that pheno.txt file had a mistake (it had the samples ID column, which shouldn't be there), so I corrected it and it worked fine, which means that the BIMBAM mean genotype file was correct.

Thanks again! :)

Ángela

**Comment by pcarbo** [comment]
@angelaparodymerino Wonderful!

**Comment by pjotrp** [comment]
I would like to replicate the error. I don't think the recent versions of gemma segfault on this, but I would like to make sure.

**Comment by pcarbo** [comment]
@pjotrp Great idea.

**Comment by pjotrp** [comment]
The code checks for the number of columns.
