### ISSUE TITLE
-bslmm 1 (linear bslmm) or -bslmm 2 (ridge regression)

### ISSUE THREAD

**Issue by angelaparodymerino** [genetics-statistics/GEMMA#108]
Hi,

I have a question about under which criteria would be better to use the option -bslmm 1 (for performing a linear bslmm) or -bslmm 2 (for ridge regression). I am working with a quantitative trait, and the only thing I found out about these two methods is that ridge regression suits better a situation in which the explanatory variables of the model (in my case I have the SNPs, and the 2 covariates: kinship and population stratification/PCs) are correlated. If I am right, kinship, population stratification and SNPs are correlated (right?) therefore, is it always better to use ridge regression instead of linear BSLMM when including population stratification and/or kinship in the model?

I would be grateful if someone can explain a bit more about these two options: linear BSLMM versus ridge regression (i.e. when to use each), or even better, about the three options that GEMMA (BSLMM) gives: linear BSLMM, ridge regression or probit BSLMM, when doing a genome wide association study.

Thanks in advance!

Kind regards,

Ángela

**Comment by pcarbo** [comment]
@angelaparodymerino No, both the ridge regression and BSLMM models would model the covariates similarly, and would correctly account for correlations between the covariates and the SNPs.

**Comment by angelaparodymerino** [comment]
Hi pcarbo,

Thanks for your answer.

So, what is the difference between using ridge regression and BSLMM? Under which criteria should I decide to use one or the other?

Thanks,

'Angela Parody-Merino

**Comment by pcarbo** [comment]
@angelaparodymerino [Our PLoS Genetics paper](http://dx.doi.org/10.1371/journal.pgen.1003264) discusses this very question. In short, the BSLMM model is more flexible, so should provide more accurate estimates across a wider range of complex traits.

**Comment by angelaparodymerino** [comment]
Ok. Thanks.

'Angela Parody-Merino
