### ISSUE TITLE
number of burn-in iterations if -w not used?

### ISSUE THREAD

**Issue by angelaparodymerino** [genetics-statistics/GEMMA#109]
Hi,

I was wondering what are the standard parameters when values for -w (burn-in iterations) and -s (number of sampling iterations that will be saved) are not indicated.

Thanks!

Ángela

**Comment by pcarbo** [comment]
@angelaparodymerino You can find the answers to your questions with `gemma -h 10`.

**Comment by angelaparodymerino** [comment]
Thanks! :)

'Angela
