### ISSUE TITLE
Gemma v0.96 issue

### ISSUE THREAD

**Issue by forevertl** [genetics-statistics/GEMMA#111]
Hi, 
I 'd like to ask a gemma issue question. I have a code as below which I can run well without problem using old version of gemma. But after I use v0.96, I cannot get it run. I got error: 'ILLegal instruction (core dumped). I use Linux server. 
my code: 

```
gemma -bfile exm1580829_1660 -k ../genoSNPs_1600.sXX.txt -lmm 4 -c age \
  sex_logtot_uas_1660.txt -n 1 -o exm1580829_tdmapct_adj_log_totuasraw
Reading Files ...
## number of total individuals = 1660
## number of analyzed individuals = 1660
## number of covariates = 4
## number of phenotypes = 1
## number of total SNPs = 1
## number of analyzed SNPs = 1
Start Eigen-Decomposition...
Illegal instruction (core dumped)
```

Do you know why this happens? Thank you very much for your help and time in advance!
Lin

**Comment by pjotrp** [comment]
Please try 0.97 prelease as described here:
https://github.com/genetics-statistics/GEMMA/issues/90.

**Comment by forevertl** [comment]
thank you. I tried 0.97 prelease and got error: 
**** DEBUG: entered in src/io.cpp at line 402 in ReadFile_cvt
**** DEBUG: entered in src/io.cpp at line 469 in ReadFile_bim
**** DEBUG: entered in src/io.cpp at line 515 in ReadFile_fam
**** DEBUG: entered in src/io.cpp at line 810 in ReadFile_bed
GSL ERROR: matrix is singular in lu.c at line 266 errno 1
it is weird since I only have one SNP and one row in .bim file. I use multiple columns for multiple phenotypes. code is as below: 
~/opt/gemma/bin/gemma -bfile exm1580829_1660 -k ../genoSNPs_1600.sXX.txt -lmm 4 -c agesex_logtot_uas_1660.txt -n 1 -o exm1580829_log_dmaraw_male_adj_log_totuasraw&

do you know how to solve it? Thank you very much!
Lin

**Comment by pjotrp** [comment]
Much better error message ;). @pcarbo can you give an opinion. The matrix is singular.

**Comment by pcarbo** [comment]
@forevertl What was the command you ran to generate the kinship matrix `genoSNPs_1600.sXX.txt`? What happens if you run GEMMA with `-lm` instead of `-lmm`? Does that work?

**Comment by pjotrp** [comment]
This is a support issue that should be continued on the mailing list:

https://groups.google.com/forum/#!forum/gemma-discussion

**Comment by pcarbo** [comment]
@forevertl We are migrating all Q&A and discussion (except for bug reports and development-related discussion) to the GEMMA mailing list. If you have any followup questions, I encourage you to subscribe to the mailing list and post your questions there. Please see:

https://groups.google.com/group/gemma-discussion

(Note it is easy to unsubcribe at any point.)
