### ISSUE TITLE
Interpretation of hyperparameters

### ISSUE THREAD

**Issue by angelaparodymerino** [genetics-statistics/GEMMA#114]
Hi,

After running a BSLMM, I used some tools for analyzing BSLMM outputs given here:  [http://romainvilloutreix.alwaysdata.net/romainvilloutreix/wp-content/uploads/2017/01/gwas_gemma-2017-01-17.pdf](url). This is the summary of the hyperparameters of my BSLMM:

hyperparam | mean | median
h | 0.115449 | 0.082885
**PVE | 0.06197 | 0.05222**
rho | 0.635796 | 0.689002
**PGE | 0.423921 | 0.398434**
pi | 0.030877 | 0.030738
n.gamma | 105.84 | 107

Could you please comments in each of my hyperparameter interpretation?

1) h (heritability) seems to be quite low (values ranges from 0 to 1). Proportion of variance in phenotypes explained by all SNPs or "chip heritability" is quite low too. This is indicating that the phenotype is not much explained by my set of SNPs (in other words, the variability of the phenotype is not well explained by the SNPs under any of the two models that BSLMM contains - LMM nor BVSR - ). 

2) I am not sure about how interpret rho. In the pdf of the link I attached at the beginning for this comment, it says that rho is the approximation to proportion of genetic variance explained by variants with major effects, and when rho is close to 0 , that means that we are more in a LMM case (highly polygenic basis of the phenotype) and when rho is close to 1, it is more a BVSR case, which means that there are a few major effects loci. I got rho = 0.6, which might mean that it is not well defined for either LMM or BSVR (??) probably because h and PVE are quite low (not much phenotypic variation explained by the set of SNPs I tested and therefore, not clear which genetic architecture is behind this phenotype). 

3) Proportion of genetic variance explained by sparse effects (PGE). I don't really understand the definition. I would have expected a definition like: proportion of genetic variance explained by alleles with sparse and major effects . Well, not sure what this parameter mean exactly. Also I got confused because I would have expected, in my case, to get a much lower PGE (taking in consideration the values of h and PVE). What is PGE telling me? I got a mean PGE = 0.41, which seems -to me- not too low.

4) pi is the proportion of variants with with non-zero effects, but not sure what does it mean that the mean value for pi = 0.03. What is pi telling me?

5) n.gamma is the number of variants with major effect. This seems easier to interpret. Well, I don't know what is the threshold to decided which SNPs are considered with major effects (over the rest with minor effects) but well, in my case, 105 SNPs have major effects over the rest.

I would be also grateful if you consider to add more comments regarding how should the outputs of BSLMM be interpreted. For example, alpha and beta columns of the *.param.txt file., are these any useful to extract conclusions or to interpret something?

And last, a kind of related question: in the *param.txt file I noticed a column 'ps'. and all the column has '-9'. What does this column refer to? position of the SNPs?

Thanks in advance,

Regards,

'Angela Parody-Merino

**Comment by pjotrp** [comment]
Hi @angelaparodymerino. 

For non development related discussions we have opened a mailing list at https://groups.google.com/forum/#!forum/gemma-discussion. Please take queries such as these to that list.

Much appreciated.

Pj.
