### ISSUE TITLE
Support for pooled genome data?

### ISSUE THREAD

**Issue by arose13** [genetics-statistics/GEMMA#115]
Do you think there will be support for pooled sample data coming anytime soon?

**Comment by pjotrp** [comment]
Please discuss on the mailing list. https://groups.google.com/forum/#!forum/gemma-discussion

**Comment by pcarbo** [comment]
@arose13 To clarify, we are migrating all Q&A and discussion (except for bug reports and development-related discussion) to the GEMMA mailing list. I encourage you to subscribe to the mailing list and post your question there. Please see:

https://groups.google.com/group/gemma-discussion

(Note it is easy to unsubcribe at any point.)
