### ISSUE TITLE
Doesn't GEMMA return random effect estimate using Univariate Linear Mixed Model?

### ISSUE THREAD

**Issue by CDsilvaA** [genetics-statistics/GEMMA#118]
Hello, I am using your software GEMMA for my analysis and I need to estimate gebv. I am using the Univariate Linear Mixed Model and I have noticed that the output doesn't return the random effect estimate (u). How can I get this values? 

Also, I tried to use the Bayesian Sparse Linear Mixed Model but it always returns a crash when the software computes the UtX: 

    ## number of total individuals = 6000
    ## number of analyzed individuals = 6000
    ## number of covariates = 1
    ## number of phenotypes = 1
    ## number of total SNPs = 560551
    ## number of analyzed SNPs = 560551
    Start Eigen-Decomposition...
    pve estimate =0.123527
    se(pve) =0.0148157
    Calculating UtX...
    Segmentation fault (core dumped)

I work with 32 processors and 250GB of memory, I don't believe that memory is a problem. The files that I used in the BSLMM is the same that I used in ULMM, so there is not error in the file. Is there any solution for that?

Thanks in advance

**Comment by pcarbo** [comment]
@CDsilvaA Thank you for your post! Can you please send your question to the [Google Group](https://groups.google.com/forum/#!forum/gemma-discussion)? We are requesting that all questions and discussion be posted in the Google Group, and Issues reserved for bug reports and feature requests.
