### ISSUE TITLE
gxe error

### ISSUE THREAD

**Issue by grzybowskim** [genetics-statistics/GEMMA#119]
Hi,

i try to perform gxe analysis but i always get error:

Reading Files ... 
Segmentation fault (core dumped)

i know there was similar error here previously so i update my OpenBLAS to newest version, but it still doesn't work. I try both GEMMA version 0.96 and 0.97. Moreover, every analysis without -gxe works fine. 

My code is:
gemma.linux -bfile chr1 -k kinship.txt -lmm 1 -n 1 2 -c cv.txt -gxe env.txt -p pheno.txt

I will be grateful for any suggestion, how can i fix this issue. 

All the best,
Marcin

**Comment by pcarbo** [comment]
@grzybowskim Thank you for your post, and your interest in GEMMA. Can you please post this same question on [the Google Group](https://groups.google.com/forum/#!forum/gemma-discussion)? Thank you.
