### ISSUE TITLE
Running GEMMA conditioning on SNPs using genotype as a covariate

### ISSUE THREAD

**Issue by slricketts** [genetics-statistics/GEMMA#121]
Hi,
I would like to run a case-control analysis in GEMMA conditioning on the top SNP hit in my GWAS dataset (association analysis run using univariate linear mixed model).  In PLINK I would do this by putting SNP genotypes (coded as 0,1,2) in a covariate file.  Can I do this in GEMMA and how should I set up the covariate file?
Many thanks!

**Comment by pcarbo** [comment]
@slricketts Can you please post to the [Google Group](https://groups.google.com/forum/#!forum/gemma-discussion) and I will answer your question? Thank you.
