### ISSUE TITLE
[Request] Support to return ebv and random effect estimate in univariate model

### ISSUE THREAD

**Issue by trprado** [genetics-statistics/GEMMA#122]
Greetings, I have a trouble when I use gemma to return the ebv and the random effect estimate.

When I try to calculate the ebv multiplying the genetic matrix and the beta estimate the values I obtain of ebv are too high, I know that is missing the random effect to complete the calculus but this high result is unexpected. In the manual does not have explanations about how to get this parameters, it have information about the random effect but it does not appear in the output. I observed that the code have a function named addBV, in prdt.cpp, it pass the genetic matrix, the random effect estimate ahd the y_prdt, but I do not understand if y_prdt is the Beta estimate or is other value because the formula to compute gebv is `G*beta+u`, where G is the genetic matrix, u is the random effect estimate and beta is the beta estimate. And why this is only available in the bayesian model? The function addBV centralized the genetic matrix, why to do so? 

An another doubt, in the manual, the beta estimative is the effect size of the marker, but is the large effect or the small effect?

Is possible to implements the support to return the parameter of random effect and ebv? Plus, can also return the residuals of the model?

Sorry the inconvenience.

**Comment by pjotrp** [comment]
Read https://github.com/genetics-statistics/GEMMA/tree/gemma-0.97-preview#reporting-a-gemma-bug-or-issue
