### ISSUE TITLE
Prebuilt GEMMA binary fails on the mouse example

### ISSUE THREAD

**Issue by Heroico** [genetics-statistics/GEMMA#125]
Hi there!

I just started using GEMMA and run into an issue. The prebuilt binary `gemma.linux`, available from http://www.xzlab.org/software.html, crashes when running on the mouse example. When I build the binary myself from the sources, it succeeds. The output from my binary seems to match that in `demos.txt` (except for header changes or new fields)

How was that binary built? I think I experience the same problem from #88 
I am working on Ubuntu 16.04.

Thanks!

PS: console output follows. Maybe there is an issue with the version of EIGEN?

```
#Prebuilt binary
~Downloads/gemma.linux -g mouse_hs1940.geno.txt.gz -p mouse_hs1940.pheno.txt -n 1 \
  -a mouse_hs1940.anno.txt -k ./output/mouse_hs1940.cXX.txt -lmm \
  -o mouse_hs1940_CD8_lmm
Reading Files ...
## number of total individuals = 1940
## number of analyzed individuals = 1410
## number of covariates = 1
## number of phenotypes = 1
## number of total SNPs = 12226
## number of analyzed SNPs = 10768
Start Eigen-Decomposition...
Illegal instruction (core dumped)
```

```
../bin/gemma -g mouse_hs1940.geno.txt.gz -p mouse_hs1940.pheno.txt -n 1 \
-a mouse_hs1940.anno.txt -k ./output/mouse_hs1940.cXX.txt -lmm \
 -o mouse_hs1940_CD8_lmm
Reading Files ...
**** DEBUG: ReadFile_anno in src/io.cpp at line 266 in ReadFile_anno
**** DEBUG: entered in src/io.cpp at line 369 in ReadFile_pheno
**** DEBUG: entered in src/io.cpp at line 624 in ReadFile_geno
## number of total individuals = 1940
## number of analyzed individuals = 1410
## number of covariates = 1
## number of phenotypes = 1
## number of total SNPs    = 12226
## number of analyzed SNPs = 10768
**** DEBUG: entered in src/io.cpp at line 1142 in ReadFile_kin
Start Eigen-Decomposition...
pve estimate =0.608801
se(pve) =0.032774
**** DEBUG: entering in src/lmm.cpp at line 1278 in AnalyzeBimbam
Reading SNPs  ==================================================100.00%
```

**Comment by pcarbo** [comment]
Hi @Heroico, thanks for your interest in GEMMA. Please try [GEMMA 0.97](https://github.com/genetics-statistics/GEMMA/releases/tag/v0.97), which was released a few days ago. Let us know if you have problems installing the new release on your computer. And please post questions to the [Google Group](https://groups.google.com/forum/#!forum/gemma-discussion).
