### ISSUE TITLE
Problems when trying to create relatedness matrix with new version

### ISSUE THREAD

**Issue by thorellk** [genetics-statistics/GEMMA#126]
Hi!

I am trying to create a relatedness matrix using the new version of gemma but run into a problem:

`gemma_v097 -g genfile_gemma.txt -p phenotype_general_gemma.txt -a snpfile_gemma.txt -gk 1 -o epistasis_matrix -maf 0`

And get the following output including error message.

`GEMMA 0.97 (2017/12/19) by Xiang Zhou and team (C) 2012-2017
Reading Files ... 
ERROR: Enforce failed for NC000915_373 in src/io.cpp at line 276 in ReadFile_anno`

I have run the same files successfully with the previous version without any problems. Is there some new requirement when it comes to how to name the variants or something similar?

Best wishes,

Kaisa

**Comment by pcarbo** [comment]
@thorellk Can you please post on the [Google Group](https://groups.google.com/forum/#!forum/gemma-discussion) and we will reply there? Also, please provide details about your operating system, and whether you downloaded the binary or compiled from source. Thank you.
