### ISSUE TITLE
The question about Bayesian

### ISSUE THREAD

**Issue by white002** [genetics-statistics/GEMMA#128]
I tried to use the BSLMM to analysis my data.
_"./gemma -bfile desktop -bslmm 3 -o bslmm"_
the window showed 'Cholesky decomposition unsuccessful in lapack_cholesky_decomp' in the analysis
Is that correct to complete the analysis?

**Comment by pjotrp** [comment]
https://github.com/genetics-statistics/GEMMA#reporting-a-gemma-bug-or-issue
