### ISSUE TITLE
Create tool for bimbam format checking

### ISSUE THREAD

**Issue by pjotrp** [genetics-statistics/GEMMA#129]
The format checking in gemma is very basic (segfaulting was the old option). We need something more rigorous as an extra tool since support questions are often related.

**Comment by pjotrp** [comment]
One thing it should check is whether all genotypes are NAs. See also https://github.com/genenetwork/genenetwork2/issues/271

**Comment by pcarbo** [comment]
From a user:

> I can agree with you that the error messages could be more informative, even in debug mode the messages did not exactly lead me to the error, I found it out by chance. Making sure that the files are the correct dimensions should of course be a no-brainer for the user really but it could probably also be included in the code so that you don’t have to spend time trouble-shooting issues like mine anymore.

**Comment by pjotrp** [comment]
Moving that to gemma2lib
