### ISSUE TITLE
In log file, question about pve, vg and ve

### ISSUE THREAD

**Issue by timflutre** [genetics-statistics/GEMMA#13]
Hi Xiang,
we used real genotypes and simulated phenotypes:
- model: y = W alpha + X beta + Z u + e where X is N=~300 individuals x P~=6000 SNPs
- u ~ N(0, sigma_u^2 K) with K estimated from equation 2.2 from Astle and Balding
- e ~ N(0, sigma_e^2 I)
- only 100 SNPs have an effect: beta = c(rnorm(n=100, mean=0, sd=1), rep(0, ncol(X)-100))
- we also fixed h2 = 0.5 and sigma_e^2 = 1, thus sigma_u^2 = (h2 \* sigma_e^2) / (1 - h2)

We fit the uLMM and get the following lines in the log file:

```
pve estimate in the null model = 0.129203
se(pve) in the null model = 0.102527
vg estimate in the null model = 33.8083
ve estimate in the null model = 71.0727
```

For the null model, I would expect pve ~= vg / (vg + ve), but it's not the case, where am I wrong?

**Comment by xiangzhou** [comment]
Hi Tim,

Actually pve = s*vg/(s*vg+ve), where s=mean(diag(K)) (see the supplementary information text in our plos genetics 2013 paper). Therefore, only when s=1, or when the genotypes are standardized before computing the kinship matrix, the equation pve=vg/(vg+ve) will hold. If the genotypes are not standardized when computing the kinship matrix, then the diagonal elements will often be close to 0.3. In this case, the estimated pve will not be vg/(vg+ve).
