### ISSUE TITLE
Suggestion: possibility to direct output directory/path

### ISSUE THREAD

**Issue by thorellk** [genetics-statistics/GEMMA#132]
Hi!

Would it be possible to include a parameter to manually set the desired output directory/file path, for example if one wants to write the output files to a temporary directory instead of the working directory etc?

Best wishes,

Kaisa

**Comment by pcarbo** [comment]
@thorellk If you run `gemma -h 2` you will see there is an option `-outdir`:

```
-outdir [path] specify output directory path (default "./output/")
```

**Comment by thorellk** [comment]
Great, thank you!

**Comment by pjotrp** [comment]
@thorellk please use the mailing list.
