### ISSUE TITLE
Error GWAS Univariate analysis

### ISSUE THREAD

**Issue by sweerasi** [genetics-statistics/GEMMA#133]
Hi,

I ran the Gemma 0.97 and got an error.
 
I used the following command to do the GWAS “~/gemma/bin/gemma -bfile BWH -k GRM -lmm  1 -o BWH_ASS” and received the following error.
“ERROR: Enforce failed for file_kin GRM: open file in src/param.cpp at line 912 in CheckParam”
 
Old version didn’t give that kind of error for the dame data. 
 
My GRM is in the original matrix format prepared using R program.
 
Highly appreciate your comments and suggestions to fix this.
 
Kind regards

Shalanee

**Comment by pjotrp** [comment]
GRM can not be opened. Please follow https://github.com/genetics-statistics/GEMMA#reporting-a-gemma-bug-or-issue

**Comment by sweerasi** [comment]
Dear Peter,

 

Thank you so much.

 

Kind regards


Shalanee
