### ISSUE TITLE
Question about LMM and BSLMM

### ISSUE THREAD

**Issue by white002** [genetics-statistics/GEMMA#134]
When I used the linear mixed model analysis, there are thousands of SNPs have the significant p-value, and I tried to adjust my raw data to normality,  but I got the same results, what problem I have to notice?

The bslmm analysis have three mode, what different in mode 1 (linear BSLMM) and mode 3 (Probit BSLMM)? I saw the Polygenic modeling with bayesian sparse linear mixed models which said the probit BSLMM is for category phenotype, can I used in quantitative traits, or just used the linear BSLMM?

**Comment by pcarbo** [comment]
@white002 Can you please send an email to the [Google mailing list](https://groups.google.com/forum/#!forum/gemma-discussion) with your question? Thank you.
