### ISSUE TITLE
rc/lmm.cpp:399: double LogL_f(double, void*): Assertion `!is_nan(P_yy)' failed

### ISSUE THREAD

**Issue by astridboehne** [genetics-statistics/GEMMA#135]
HI
I am running gemma on different  subsets of individuals and get in several cases this error using

gemma: src/lmm.cpp:399: double LogL_f(double, void*): Assertion `!is_nan(P_yy)' failed.

The command I am using is

gemma -bfile $SUB -gk 1 -o $SUB
mv output/ gemma_lmm_gemmamatrix/
gemma -bfile $SUB -k $TMPDIR/gemma_lmm_gemmamatrix/output/$SUB.cXX.txt \
-lmm 4 -o ${SUB}_gemma_lmm_gemmamatrix_${PHENOTYPE}

I get the relatedness matrix but the lmm calculation fails
I am using the latest version 0.97 on a unix system

Looking forward to your reply
Best
Astrid

**Comment by pcarbo** [comment]
@astridboehne I saw your question on the Google group. I will respond there. Thank you.
