### ISSUE TITLE
Recent versions of gemma are slower

### ISSUE THREAD

**Issue by pjotrp** [genetics-statistics/GEMMA#136]
As referred in #130 creating a new issue here. @pcarbo is 0.96 also faster?

**Comment by pcarbo** [comment]
@pjotrp GEMMA v0.96 is also faster (total runtime was 73 seconds). So it must be a change that was introduced after v0.96.

**Comment by pjotrp** [comment]
Thanks confirming. I am not on Macos, so had to rule that out. We did change some calls to BLAS etc. Culprit should be pretty obvious.

**Comment by pjotrp** [comment]
Hi @pcarbo, it is interesting to compare 0.96, 0.97 and 0.98-prerelease. I have some metrics here https://github.com/genenetwork/GEMMA/blob/gemma-0.98-preview/test/performance/releases.org

Somehow lapack bled into the 0.97 release. So openblas was not used to full potential. A bit embarrassing for someone who claims to control the dependency graph(!?)

0.96 is a single core Eigenlib version and 0.97 went multi-core with openblas. Unfortunately I linked in lapack and an older BLAS which slowed things down. In 0.98 openblas is mostly used and is faster.

I can't comment on the MacOS versions, but it is good to check with ldd what was linked in. Another reason not to do static releases.
