### ISSUE TITLE
output file with kinship has extra column

### ISSUE THREAD

**Issue by timflutre** [genetics-statistics/GEMMA#14]
Hi Xiang,
I am running v0.94. When I load in R the file `kinship.cXX.txt` or `kinship.sXX.txt`, I can see that there is an extra column.
In the code section starting at [line 627 of param.h](https://github.com/xiangzhou/GEMMA/blob/master/src/param.cpp#L627), I think, you shouldn't write the tab `\t` after each number. Instead, for each line, you should write the first number, and then enter into a loop which write the tab followed by the number corresponding to this iteration.

Tim

ps: sorry, I'm waiting for my sysadmin to install LAPACK and other libraries to be able to compile GEMMA by myself. Otherwise, I'd have done a pull request...

**Comment by xiangzhou** [comment]
I see. I will fix it. Thanks. I was able to read these matrices in R correctly before, so never thought an extra tab would be a problem.

**Comment by pcarbo** [comment]
@xiangzhou It looks like the kinship files still have a tab or space at the end of each line. Can you fix this?

**Comment by wanyuac** [comment]
Not only does the kinship file has this redundant tab at the end of each line, but also happens in the eigenU.txt file in the outputs of eigen-decomposition.

**Comment by pjotrp** [comment]
Should be fixed now.
