### ISSUE TITLE
Kinship: gsl: init_source.c:29: ERROR: matrix dimension n1 must be positive integer

### ISSUE THREAD

**Issue by sariya** [genetics-statistics/GEMMA#140]
I'm trying to generate kinship using Gemma (Version 0.96, 05/17/2017)

./gemma -bfile indep -gk 1 -o kinship

Error: 
Reading Files ...
error! number of analyzed individuals equals 0.
gsl: init_source.c:29: ERROR: matrix dimension n1 must be positive integer
Default GSL error handler invoked.
Aborted

1569 individuals
142620 SNPs

uname -a
Linux 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux

Don't know what's wrong. The phenotype column in .fam file is -9 for most of the individuals.

**Comment by pjotrp** [comment]
See https://github.com/genetics-statistics/GEMMA#reporting-a-gemma-bug-or-issue

Please use a more recent version of gemma and ask questions in Google groups.

**Comment by pjotrp** [comment]
OK, I am reopening support requests.  The google group, however, is more appropriate.

**Comment by sariya** [comment]
Got it running. -9 Phenotype doesn't go well with Gemma. Thanks.

**Comment by pjotrp** [comment]
Thanks for reporting back!
