### ISSUE TITLE
Estimate of Variance Components

### ISSUE THREAD

**Issue by mengnanchang** [genetics-statistics/GEMMA#143]
I’m working on a research project. We would like to apply GEMMA on the data. I read the GEMMA manual when i use the program. However, we are not sure about the connection between the output and variance components. I would like to ask two questions in order to clarify it. 

1) Is there a way to obtain the tau and lambda in the Univariate Linear Mixed Model from GEMMA? (p.5 on GEMMA manual)

2) If i use the same quantitative traits and the same marker genotypes in both ULMM and MLMM (o.5 on GEMMA manual), where we have two more quantitative traits for MLMM, is there a way to connect the variance components between the two models? (e.g., in this scenario, can i connect the tao or lambda in ULMM to some values in Vg or Ve in MLMM?)

I also attached the ULMM (black_no_covariate_LpA.log.txt) and MLMM (black_no_covariate_All_Three.log.txt) log files, if it is easier to explain. 
[black_no_covariate_All_Three.log.txt](https://github.com/genetics-statistics/GEMMA/files/1810972/black_no_covariate_All_Three.log.txt)
[black_no_covariate_LpA.log.txt](https://github.com/genetics-statistics/GEMMA/files/1810973/black_no_covariate_LpA.log.txt)

Thanks!

**Comment by pcarbo** [comment]
@mengnanchang 1. I believe you could work out what lambda and tau are from the outputs vg, ve and/or pve in the log.txt file, but I don't immediately know the formula for doing this. It is on our "to do" list to provide more comprehensive output of these quantities, but we don't have a timetable for that to be implemented.

2. Yes, these quantities are comparable, but you would have to refer to the Nature Methods for exactly how V and Ve and defined in the multivariate phenotype model.
