### ISSUE TITLE
fitting a matrix as random effect

### ISSUE THREAD

**Issue by irn-alex** [genetics-statistics/GEMMA#144]
I want to fit a second matrix as a random effect as well as a GRM (genomic relationship matrix) in univariate GWAS. Is it possible in GEMMA?

**Comment by pcarbo** [comment]
@irn-alex Yes, it is possible, although this feature is not as well developed and documented as some of the other GEMMA features. Your command command will look something like this:

```bash
gemma -p pheno.txt -vc 2 -mk vc.txt
```

in which `vc.txt` looks something like this:

```bash
$ cat vc.txt
kinship1.txt
kinship2.txt
```

The outputted `log.txt` file from the gemma command will contain the variance component parameter estimates, which you can use to compute a "combined" relatedness/kinship matrix, e.g., in R,

```
Kcombined <- s1*K1 + s2*K2
```

where `s1` and `s2` are the sigma2 estimates corresponding to the first and second kinship matrices. You can then use the combined kinship matrix as input to subsequent association analyses.

See `gemma -h 6` for more details.
