### ISSUE TITLE
gxe issue

### ISSUE THREAD

**Issue by jsmithcvm** [genetics-statistics/GEMMA#146]
We have been having an issue with the gxe command within univariate mixed model associations. 
The command line we are using consists of -g genotypefile -p phenotypefile -n 1 -k kinshipmatrix -a annotationfile -lmm 4 -gxe environmentalcovariate -c fixedcovariate -o outputfilename

For the gxe environmental variable it is formatted as a single column consisting of Zone1 through Zone9
The fixed covariate file is sex based with the intercept column first, sex (M or F) in the second column

Prior to this we had done a linear mixed model without the gxe variable, but with a covariate file that had intercept, zone, sex columns in that order.
The linear mixed model without the gxe option runs fine with what appears to be a logical output.

The gxe results have nan outputs for every p-value, se, and beta as well. The l_remle and l_mle outputs are all 1.0e+05 indicating all genotype interaction and no environmental interaction. There are no error messages being displayed. We are using version 0.96.

**Comment by pcarbo** [comment]
@jsmithcvm Please try version 0.97 which is available [here](https://github.com/genetics-statistics/GEMMA/releases), and let us know if you are having trouble installing it.
