### ISSUE TITLE
Bug when phenotypes are missing?

### ISSUE THREAD

**Issue by astridboehne** [genetics-statistics/GEMMA#152]
Dear Gemma developers, 
we were in contact with you before concerning the error message "gemma: src/lmm.cpp:399: double LogL_f(double, void*): Assertion `!is_nan(P_yy)' failed."
We tried to fix our relatedness matrix. However, I then realized that using the same bed and bim files but different fam files will give a different matrix. Which I figures from the manual is correct. However, as soon as the fam file has an individual with a missing phenotype, the lmm fails with the error above. So it is not per se the data but the fact that the fam file has missing values. Excluding those individuals from bed and bim file solves this or changing the phenotype also. Is there a way to calculate the matrix independent of the phenotype? We are testing several phenotypes on the same set of genotypes but with different individuals being missing for different phenotypes and would like to avoid generating each time a new bed/bim file for those cases where one individual is missing for one phenotype....Thanks for any advice

**Comment by pcarbo** [comment]
@astridboehne Thanks for reporting this bug. To make sure I understand, what you are saying is that the relatedness matrix computation gives you an error whenever one or more of the phenotypes are missing?

> Is there a way to calculate the matrix independent of the phenotype? We are testing several phenotypes on the same set of genotypes but with different individuals being missing for different phenotypes and would like to avoid generating each time a new bed/bim file for those cases where one individual is missing for one phenotype.

Currently, GEMMA does not have this feature. I agree it would be useful.

**Comment by pjotrp** [comment]
The workaround is to create a fake phenotype for every individual and compute K. Currently missing values are removed from K. I am planning to add an option which allows you to compute K without looking at phenotypes as part of #155.
