### ISSUE TITLE
Executable version Permission denied

### ISSUE THREAD

**Issue by yiminghu** [genetics-statistics/GEMMA#154]
Tried the executable version (0.96) on both a linux cluster and my own laptap, received the 'Permission denied' error. Is there anyway to resolve this?

**Comment by pcarbo** [comment]
@yiminghu Try running `chmod 700 <file>` where `<file>` is the GEMMA executable. Does that fix the problem?

Also, I recommend using the latest release (version 0.97).

**Comment by yiminghu** [comment]
It works! Thanks a lot! I have tried to use 0.97 but ran into the same issue as https://github.com/genetics-statistics/GEMMA/issues/142. Seems like some environment issue on the cluster I used (I guess). Although running in a clean bash solves the problem, however, I need to run BSLMM for many jobs. I also found that by running `unset LD_LIBRARY_PATH;` first could also make it work but would still prefer to run the executable one. In term of BSLMM, does 0.96 and 0.97 yield the same performance? Thanks!

**Comment by pcarbo** [comment]
@yiminghu Please see 
[here](https://github.com/genetics-statistics/GEMMA/files/2106421/gemma.linux.gz)
 for a precompiled binary executable for GEMMA 0.97---we are not making it widely available in order to encourage people to use the Guix installation on Linux.

**Comment by yiminghu** [comment]
Thanks a lot! I could install 0.97 on my cluster it only works when I unset LD_LIBRARY_PATH. And I found the precompiled 0.96 seems to run faster then 0.97. Hope precompiled 0.97 is even faster. 😂

Thanks a lot for the help!

Yiming

**Comment by pjotrp** [comment]
For speed use the -no-check option. See #136. It is way faster than 0.96.

#142 suggest how to clean/sanitize the environment by resetting environment variables.

    env -i /bin/bash --login --noprofile --norc

any Linux admin can do this. Clusters introduce an unhealthy environment with modules.
