### ISSUE TITLE
GSL error when changing fam file

### ISSUE THREAD

**Issue by astridboehne** [genetics-statistics/GEMMA#157]
Hi again,
We were in contact concerning the relatedness matrix issue when phenotypes are missing.
I redid all my input files excluding individuals with missing phenotypes, generated new bed, bim and fam files and rerun gemma.
My lm works fine, the relatedness matrix is also generated, however, when I use a categorical phenotype and the lmm I get this error
GSL ERROR: function value is not finite in brent.c at line 57 errno 9
No issue using the exact same genotype data and relatedness matrix in a lmm with a different, quantitative phenotype.
I have this issue with three independent (small) datasets.
The lm is working as is another phenotype so it cannot be the input files.
Any advice is appreciated
Best
Astrid

**Comment by pcarbo** [comment]
I responded to this in the Google group.
