### ISSUE TITLE
gemma 0.97 warnings when generating relatedness matrix

### ISSUE THREAD

**Issue by forevertl** [genetics-statistics/GEMMA#158]
when I use gemma 0.97 to generate relatedness matrix, i got the matrix created and also got the warning as below. May I trust and use the matrix? If no,what does it mean and what should I do. Thank you very much for your help and time in advance.
thanks,
Lin
ltong@bsdad.uchicago.edu@phs-vms19:~/phsfiles/groups/Projects/GEMS/EPIC_array/LinT_analysis/GxE_As_probes_EPIC>~/gemma/bin/gemma -bfile 1kg_imputed_r2gtp3_EPIC_order_389 -gk 2 -o relatedness_EPIC389
GEMMA 0.97 (2017/12/27) by Xiang Zhou and team (C) 2012-2017
Reading Files ...
## number of analyzed SNPs         =  8643552
Calculating Relatedness Matrix ...
================================================== 100%
**** DEBUG: Ratio |eigenmax|/|eigenmin| suggests matrix is ill conditioned for double precision
**** DEBUG: Abs eigenvalues [Min 1.50288e-15, 1.50288e-15 ... 1.6112 Max] Ratio (1.6112/1.50288e-15) = 1.07208e+15
**** DEBUG: Eigenvalues [Min 1.50288e-15, 1.50288e-15 ... 1.6112 Max]
**** WARNING: K is ill conditioned! in src/gemma.cpp at line 1889

**Comment by pjotrp** [comment]
It tells you that you should not use this K.
