### ISSUE TITLE
gemma 0.97 gxe analysis walt test p-value issue

### ISSUE THREAD

**Issue by forevertl** [genetics-statistics/GEMMA#159]
when i ran gxe analysis using old version of gemma, i got similar p values comparing p_walt, p_lrt and p_score. Now I use the same data,same code, replicate the analysis vis gemma 0.97. I get the exact same beta and se. Very similar p_lrt as I got previously using old version of gemma. very similar p_score as I got previously using old version of gemma. but quite different p_walt vs. before. Now the p_walt columns are all around 0.1 and is quite different vs. p_socre and p_lrt. also it is different vs. previous p_walt from old vertion of gemma. my code is as below.
for chr in $(seq 22 22); do ~/gemma/bin/gemma -bfile QC_ori_order_mafp01_heals3364_chr${chr} -k relatedness_3364.sXX.txt -lmm 4 -maf 0 -c sexagebatch_3364.txt  -gxe quartile_ordinary_uascr_3364.txt  -o test_chr${chr} & done;
thank you for your help and time in advance.
thanks,
Lin

**Comment by pjotrp** [comment]
Thanks Lin, note the newer versions of gemma introduced an extra column. Did you account for that?

If you still see a problem, please tell me the exact versions of gemma you are using.

**Comment by forevertl** [comment]
Hi Pjotrp, 
thank you for your reply. I find an extra column called 'logl_H1' in my .assoc.txt output file. But I do not know how to adjust for it to get correct p_wald. I searched 'logl_H1' in the gemma manual and didn't find it. Could you let me know how to adjust for it? does it mention in the manual?  I use the version 0.97 (2017/12/27). thank you for your help!
Lin
