### ISSUE TITLE
gxe analysis: warning for kinship matrix

### ISSUE THREAD

**Issue by forevertl** [genetics-statistics/GEMMA#167]
Hi, 
when I generate the kinship matrix via gemma, I do not get warning message. but when I use the kinship for gxe model with code below. I got warning as below. I was told that means that kinship matrix can not be used. I am wondering if there is any solution. I always get this kind of warning when generating kinship matrix. thank you for your help in advance. 
thanks, 
Lin

```
code: gemma -bfile all -n 1  -k relatedness_5354.sXX.txt -lmm 4 -maf 0.01 -c agesex.txt  -gxe ln_uasgmcr.txt  -o out & done;
warning: 
Start Eigen-Decomposition...
pve estimate =0.134164                             0%
se(pve) =0.550095
## number of total individuals = 5354              0%
## number of analyzed individuals = 388
## number of covariates = 3
## number of phenotypes = 1
## number of total SNPs/var        = 13641405
## number of analyzed SNPs         =  8571210
**** DEBUG: Ratio |eigenmax|/|eigenmin| suggests matrix is ill conditioned for double precision
**** DEBUG: Abs eigenvalues [Min 6.43263e-16, 6.43263e-16 ... 1.60684 Max] Ratio (1.60684/6.43263e-16) = 2.49795e+15
**** DEBUG: Eigenvalues [Min -6.43263e-16, -6.43263e-16 ... 1.60684 Max]
**** WARNING: K is ill conditioned! in src/gemma.cpp at line 2559
```

**Comment by pjotrp** [comment]
https://www.mathworks.com/matlabcentral/answers/266467-when-is-a-matrix-ill-conditioned

**Comment by pcarbo** [comment]
@forevertl This is a warning only, and doesn't necessarily mean there is an issue with your GEMMA results.
