### ISSUE TITLE
gxe analysis output main effect?

### ISSUE THREAD

**Issue by forevertl** [genetics-statistics/GEMMA#168]
Hi,
I would like to ask a question. when I run gxe interaction analysis, I get the interaction term effect from the output file. I am wondering if there is an option that I also can see the main effect estimate (g and e term) in the gxe model from the output? thank you. 
Lin

**Comment by pcarbo** [comment]
@forevertl To obtain this estimate, you would need to run GEMMA without the `-gxe` option.
