### ISSUE TITLE
Breeding value calculates in GEMMA

### ISSUE THREAD

**Issue by white002** [genetics-statistics/GEMMA#170]
Hi
I used the BSLMM model to analysis the data, and it made 5 output files including file.param, file.bv, file.hyp ....... 
Can I calculate the file.bv in LMM?
If I can't calculate the breeding value (BV) on LMM, do you have any suggest softwares to calculate the BV with your LMM output? 

Lin

**Comment by pjotrp** [comment]
Thank you for using GEMMA.

For non-development questions please use our [mailing list](https://groups.google.com/forum/#!forum/gemma-discussion). 

For the use of this issue tracker see also our [README](https://github.com/genetics-statistics/GEMMA#reporting-a-gemma-bug-or-issue).
