### ISSUE TITLE
GEMMA 0.97 installation problem

### ISSUE THREAD

**Issue by Svijayrag** [genetics-statistics/GEMMA#171]

**Comment by Svijayrag** [comment]
I am trying to install a precompiled binary version of  GEMMA 0.97 on my MAC OS (High Sierra). After downloading the generic tar bz file, I ran the following commands on Terminal:

$sv112 tar xvjf gemma-git-gn2-0.97-c760aa0-generic-x86_64.tar.bz2

While I had no issues unpacking the file, I ran into errors after running the installation command:
sv112$ ./install.sh ~/gemma
./installer/bin/traveling-ruby-20141215-2.1.5-linux-x86_64/bin/ruby: line 6: /Users/sv112/Downloads/installer/bin/traveling-ruby-20141215-2.1.5-linux-x86_64/bin.real/ruby: cannot execute binary file
./installer/bin/traveling-ruby-20141215-2.1.5-linux-x86_64/bin/ruby: line 6: /Users/sv112/Downloads/installer/bin/traveling-ruby-20141215-2.1.5-linux-x86_64/bin.real/ruby: Undefined error: 0

I feel like I am missing some basic trick. Please suggest a fix.
Thanks!
Sri

**Comment by pjotrp** [comment]
You are using the Linux installer. Use the macos one.
