### ISSUE TITLE
 GEMMA 0.97 installation problem (macosx)

### ISSUE THREAD

**Issue by yupinglin123** [genetics-statistics/GEMMA#172]
Does anyone know how to install macosx version of GEMMA(0.97) on MacBook Sierra 2.7 GHz Intel Core i5? 

Below are the commands and errors on Terminal:
1.$wget https://github.com/genetics-statistics/GEMMA/releases/download/v0.97/gemma.macosx.gz
2.$gunzip gemma.macosx.gz -> get the unzipped version of gemma.macosx
3. ./gemma.macosx -> get Persmission denied  error 
4. chmod +x gemma.macosx -> run the third step again -> get ./gemma.macosx: cannot execute binary file: Exec format error

As far as I know the file format of gemma.macosx is **Mach-O 64-bit x86_64 executable**. Please give me some suggestions to fix the problem. 

Thanks very much 

Yu-Ping

**Comment by pjotrp** [comment]
Thank you for using GEMMA.

For non-development questions please use our [mailing list](https://groups.google.com/forum/#!forum/gemma-discussion). 

For the use of this issue tracker see also our [README](https://github.com/genetics-statistics/GEMMA#reporting-a-gemma-bug-or-issue).
