### ISSUE TITLE
Compiling GEMMA 0.97 with local version of OpenBlas?

### ISSUE THREAD

**Issue by e-jorsboe** [genetics-statistics/GEMMA#174]
Hi,

I have tried compiling GEMMA 0.97 using a local version of OpenBlas. I have therefore made the following edits to the Makefile that comes with the source code of GEMMA 0.97:

1.
$(OUTPUT): $(OBJS)
	$(CPP) $(CPPFLAGS) $(OBJS) -L/path/to/local/openblas $(LIBS) -o $(OUTPUT)

(Where I of course have specified the correct path to the OpenBlas library).

2.
I have also set OPENBLAS_INCLUDE_PATH to the local OpenBlas library.

I have succeeded in compiling the code, but when I run the constructed binary I get the following error:

bin/gemma: error while loading shared libraries: libopenblas.so.0: cannot open shared object file: No such file or directory

So how do I compile GEMMA 0.97 with a local version of OpenBlas?

**Comment by pcarbo** [comment]
@e-jorsboe When linking to a shared library, you also have to tell the system where to find that shared library. Usually it is by editing the `LD_LIBRARY_LIBRARY` environment variable. Let us know if that solves your issue.

**Comment by pjotrp** [comment]
Read INSTALL document.
