### ISSUE TITLE
Interpretation of BSLMM output

### ISSUE THREAD

**Issue by guillaume-ramstein** [genetics-statistics/GEMMA#178]
Hello, I had a question about the output from BSLMM in GEMMA.
When supplying both a genotype matrix and a relationship matrix G to gemma -bslmm 1, do alpha and beta correspond to effects conditioned on G (such that y = X.alpha + X.beta + u + e; u being polygenic effects and e being errors) or does alpha correspond to polygenic effects as captured by G (such that y = X.beta + u + e and alpha_hat = X'G^-1u_hat)?
Thanks

**Comment by pjotrp** [comment]
Thank you for using GEMMA.

For non-development questions please use our [mailing list](https://groups.google.com/forum/#!forum/gemma-discussion). 

For the use of this issue tracker see also our [README](https://github.com/genetics-statistics/GEMMA#reporting-a-gemma-bug-or-issue).
