### ISSUE TITLE
compiler warnings

### ISSUE THREAD

**Issue by emyr666** [genetics-statistics/GEMMA#18]
Large numbers of compiler warnings are produced during compilation. The makefile has -Wall which prints these - all well and good. If you are interested in producing warnings then any that are produced should be fixed so that the code compiles clean.
Compiler warnings flagged up by -Wall can sometimes give rise to subtle bugs at run-time so it's prudent to make sure that any code compiles clean.

**Comment by emyr666** [comment]
Given this is C++11, it's also worth addin -Weffc++

**Comment by pcarbo** [comment]
@emyr666 Thank you for raising this issue. 

@xiangzhou I ran `make -f Makefile.osx` on my MacBook Pro (Mac OS X 10.11, Apple LLVM version 8.0.0)  with the flags `-Wall -Weffc++`, as suggested by @emyr666. In total, I generated about 54 warnings (see file below containing the full output of running `make`). You probably don't need to address all of these warnings, and some of these warnings may never cause problems in practice, but it would be very helpful if you could make a reasonable effort to fix them (e.g., start with the "uninitialized variable" warnings).

[make-macosx-warnings-9-may-2017.txt.gz](https://github.com/xiangzhou/GEMMA/files/987573/make-macosx-warnings-9-may-2017.txt.gz)

**Comment by pjotrp** [comment]
https://github.com/xiangzhou/GEMMA/pull/56 fixes all warnings, including the annoying ones from Eigen, and makes warning checkings optional
