### ISSUE TITLE
GEMMA 0.98 fails with: "N>0 in src/fastblas.cpp"

### ISSUE THREAD

**Issue by voichek** [genetics-statistics/GEMMA#182]
Hi,

Using gemma 0.98, I got the following error massage:

> ERROR: Enforce failed for N>0 in src/fastblas.cpp at line 197 in fast_cblas_dgemm

The same parameters configuration works with the 0.96 version.

Am I doing something wrong or is it a bug?

If needed, the files used for this run can be downloaded from [here](https://drive.google.com/drive/folders/14DavBkzIELU-IcRtlQrNfgRdhlImbGCe?usp=sharing).

**Run with 0.98**
```
$ gemma-0.98-linux-static -bfile test -lmm 2 -k kinship.cXX -maf 0.05 -miss 0.5 -o test_output
GEMMA 0.98 (2018-09-28) by Xiang Zhou and team (C) 2012-2018
Reading Files ...
## number of total individuals = 876
## number of analyzed individuals = 876
## number of covariates = 1
## number of phenotypes = 1
## number of total SNPs/var        =  1000000
## number of analyzed SNPs         =  1000000
Start Eigen-Decomposition...
pve estimate =0.969141
se(pve) =0.0263771
ERROR: Enforce failed for N>0 in src/fastblas.cpp at line 197 in fast_cblas_dgemm
```

**Run with 0.96:**
```
$ gemma -bfile test -lmm 2 -k kinship.cXX -maf 0.05 -miss 0.5 -o test_output
Reading Files ...
## number of total individuals = 876
## number of analyzed individuals = 876
## number of covariates = 1
## number of phenotypes = 1
## number of total SNPs = 1000000
## number of analyzed SNPs = 1000000
Start Eigen-Decomposition...
pve estimate =0.969141
se(pve) =0.0263771
Reading SNPs  ==================================================100.00%

$ gemma

*********************************************************
  Genome-wide Efficient Mixed Model Association (GEMMA)
  Version 0.96, 05/17/2017
  Visit http://www.xzlab.org/software.html For Updates
  (C) 2017 Xiang Zhou
  GNU General Public License
  For Help, Type ./gemma -h
*********************************************************
```

Thanks for the help,
Yoav Voichek
Detlef Weigel's lab, MPI

**Comment by pjotrp** [comment]
That particular enforce makes sure we get no integer overflows with GSL matrix. The old gemma had no such check, so you are risking results that are wrong by using it. Since you are only doing 876 individuals I suggest to split the SNP dataset into smaller chunks. That should work.

GEMMA will support larger SNP datasets in the near future. I'll raise a new issue for it. At this point, unfortunately, the full genotypes are loaded in one single matrix.

**Comment by pjotrp** [comment]
@voichek thanks for reporting. Turns out that if the number of SNPs is an exact multiple of computational batches (sized 20,000) you will hit this error. Gemma 0.96 did not have this problem. The workaround until the next release is to add a SNP. Sorry about that!

**Comment by voichek** [comment]
Thanks for the quick response!
