### ISSUE TITLE
GEMMA miscounts rows in covariates file

### ISSUE THREAD

**Issue by lukeholman** [genetics-statistics/GEMMA#186]
Hey there,

I get this error: `error! number of rows in the covariates file do not match the number of individuals. 185`

I checked the file, and it does indeed have 185 rows when opened in R or Sublime Text. I checked the FAM file, and there are indeed 185 individuals with non-missing phenotypes. 

I guess it is some arcane problem involved the end-of-line character? 

Cheers

**Comment by lukeholman** [comment]
[covariate_file_for_GEMMA_transcriptome.txt](https://github.com/genetics-statistics/GEMMA/files/2564564/covariate_file_for_GEMMA_transcriptome.txt)

**Comment by pjotrp** [comment]
That file is fine, indeed. I think the # individuals differs. Maybe that file has a problem. Sorry, gemma is not very clear here.

**Comment by lukeholman** [comment]
Is there a way to Gemma to tell me how many individuals it thinks are in the FAM file? The error message just counts the number of rows in the covariate file. I tried adding a row of covariates and subtracting a row, but no effect.

**Comment by pjotrp** [comment]
I know, I just added a patch to that effect. If you run without covariates it should show the number of individuals. I hope you are using 0.98. Use the -debug and -check options.

**Comment by lukeholman** [comment]
Hey there, I got a chance to look into this now. I ran the same model with no covariates file, and it says that the number of individuals is 185. And as you said above, the covariates is fine, and it has exactly 185 rows. I still get this message:

```
Reading Files ... 
error! number of rows in the covariates file do not match the number of individuals. 185
error! fail to check data. 
```

I don't know how to "-debug and -check options", as they are not mentioned in the manual, and entering them in the same command as the model does nothing. 

Cheers

**Comment by prasunanand** [comment]
I think the covariates file has spaces and GEMMA expects tabs.

https://github.com/genetics-statistics/GEMMA/blob/master/src/gemma_io.cpp#L462

Please replace spaces in covariates file with tabs, and try running it. I hope it helps.

**Comment by lukeholman** [comment]
Thanks! I did use spaces, though oddly, it has worked ok in the past with
other tests. I will try with tabs next time. Maybe this could be added to
the GEMMA manual? There is a very long section explaining how to set up the
files, but it does not say whether they should be tab or space delimited
(at least, I did CMD+F for the words "tab", "space", and "delimited" and
there was nothing).

Cheers

**Comment by pjotrp** [comment]
In principle gemma should allow for all whitespace and comma's (ignoring i8n). I think it is an eol thing. It would help if I could reproduce the problem. I'll promise to look at it with data.
