### ISSUE TITLE
GSL error breaks LOCO

### ISSUE THREAD

**Issue by danfulop** [genetics-statistics/GEMMA#192]
I raised this issue in the forum (https://groups.google.com/forum/#!topic/gemma-discussion/tbB8DlVdYKg). I am running LOCO on a somewhat small mouse dataset where the mice are all somewhat related, and I get an error when LOCO hits chromosome 9.

I’m trying to run LOCO with the gemma-wrapper. I’ve tried it both with the latest GEMMA Linux binary (v0.98.1), and with conda-installed GEMMA (v0.98) both on a Linux machine and on a Mac.

I get a GSL error for conda-installed GEMMA and a src/fastblas.cpp error for the latest GEMMA Linux binary.

For the latest GEMMA Linux binary, the error is this:

```
ERROR: Enforce failed for N>0 in src/fastblas.cpp at line 197 in fast_cblas_dgemm
./gemma-wrapper-0.98.1/bin/gemma-wrapper:279:in `block in <main>': exit on GEMMA error 2 (RuntimeError)
    from ./gemma-wrapper-0.98.1/bin/gemma-wrapper:331:in `call'
    from ./gemma-wrapper-0.98.1/bin/gemma-wrapper:331:in `block in <main>'
    from ./gemma-wrapper-0.98.1/bin/gemma-wrapper:356:in `call'
    from ./gemma-wrapper-0.98.1/bin/gemma-wrapper:356:in `block in <main>'
    from ./gemma-wrapper-0.98.1/bin/gemma-wrapper:355:in `each'
    from ./gemma-wrapper-0.98.1/bin/gemma-wrapper:355:in `<main>'
```

For conda-installed GEMMA the error is this:

```
GSL ERROR: second dimension must be non-zero in ./submatrix_source.c at line 41 errno 4
/Library/Ruby/Gems/2.3.0/gems/bio-gemma-wrapper-0.98.1/bin/gemma-wrapper:279:in `block in <top (required)>': exit on GEMMA error 2 (RuntimeError)
	from /Library/Ruby/Gems/2.3.0/gems/bio-gemma-wrapper-0.98.1/bin/gemma-wrapper:331:in `block in <top (required)>'
	from /Library/Ruby/Gems/2.3.0/gems/bio-gemma-wrapper-0.98.1/bin/gemma-wrapper:356:in `block in <top (required)>'
	from /Library/Ruby/Gems/2.3.0/gems/bio-gemma-wrapper-0.98.1/bin/gemma-wrapper:355:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/bio-gemma-wrapper-0.98.1/bin/gemma-wrapper:355:in `<top (required)>'
	from /usr/local/bin/gemma-wrapper:22:in `load'
	from /usr/local/bin/gemma-wrapper:22:in `<main>'
```

I’d be happy to share the data files for you to reproduce the error. Just ask me.

Thanks!!
Dan.

**Comment by pjotrp** [comment]
Yes, the data would be useful. I'll treat it as confidential.

**Comment by pjotrp** [comment]
There is a problem with the data. Apparently chr 9 ends up being empty. The gemma-wrapper does not like it when gemma bails out (for good reason, there are no SNPs for chr 9). 

There is also a plan to create a python wrapper that can validate data. I am thinking this is a good time to start on that ;).

What is the actual command you are giving? And you can send me the data - it helps.

**Comment by danfulop** [comment]
Okay, so it looks like the plink conversion to bimbam might've messed
things up, as for example there are only 3 SNPs for chr 9 in the snp file.

**Comment by pjotrp** [comment]
So, in short, when gemma errors the gemma-wrapper bails out (too). I think this is what it should do. The deeper problems we have to solve anyway. It is an interesting question what gemma should do when data is invalid.For progress see #166.

**Comment by wushishi544** [comment]
I am a new user of gemma. I met a difficult when I prepared the input files (geno.txt.gz, BXD_snps.txt and covariates.txt). I am really wondering how can I get these three files. I have saw the BXD_* files that the software provided, but I still feel confused.  
Sincerely hope to get your help. Thanks!
