### ISSUE TITLE
GEMMA with pruned GRMs

### ISSUE THREAD

**Issue by bstpourcain** [genetics-statistics/GEMMA#198]
I would like to run GEMMA with a pruned GRM setting off-diagonal values with <0.05 to 0, as in GCTA mlma. Is it possible to implement this option in GEMMA? Or, can I just simply use GCTA GRMs? Any guidance as to how to manipulate GRMs in GEMMA would be really helpful,

Beate

**Comment by pjotrp** [comment]
GRMs are simple matrix files. Just generate one with GEMMA and you can see that.
