### ISSUE TITLE
Reading SNPs Error

### ISSUE THREAD

**Issue by glagunas** [genetics-statistics/GEMMA#204]
Greetings,

I have encountered an interesting error when running the Univariate Linear Mixed Models. I reran the same data by parsing out SNPs that had a minimum allele frequency of 0 thinking this could be an issue but that didn't solve the issue. I have also run gemma before using the same parameters so I think it is an issue with how my input is being read.

Command
`~/shared/gemma/bin/gemma -bfile all.species -k mdist -lmm 4 -o results
`

Error

`Reading SNPs                                                    0.00%Reading SNPs  =                                                 2.57%Reading SNPs  ==                                                5.13%Reading SNPs  ===                                               7.70%gsl: newton.c:74: ERROR: derivative is zero
Default GSL error handler invoked.
/var/spool/slurmd/job5413970/slurm_script: line 33: 22781 Aborted                                               `

Any suggestions would be appreciated.

G

**Comment by glagunas** [comment]
Update: I found that the error is occurring in the P-Wald test portion of -lmm since it functions perfectly when I run a -lmm 3

**Comment by pjotrp** [comment]
Do you mind sending a sample that reproduces this error?

**Comment by pjotrp** [comment]
For lack of info
