### ISSUE TITLE
n*3 relationship matrix

### ISSUE THREAD

**Issue by irn-alex** [genetics-statistics/GEMMA#207]
Does n*3 relationship matrix work properly in linear mixed model GWAS?
In an example I couldn't run the job with n * 3 matrix, but n * n works fine.
Below is the command examples:

./gemma-0.98.1 -bfile test -km 1 -k full.grm -lmm 1 -o test1    
 (full.grm is an n*n matrix, this command works fine.)

./gemma-0.98.1 -bfile test -km 2 -k lower.grm -lmm 1 -o test2    
(lower.grm is an n*3 matrix, this command doesn't work)
 
Error: Enforce failed for file_kin lower.grm

Thanks
Alex

**Comment by pjotrp** [comment]
I don't think we do ;)
