### ISSUE TITLE
Why don't output marker R2(pve of marker)?

### ISSUE THREAD

**Issue by xiekunwhy** [genetics-statistics/GEMMA#208]
Hi,

Why don't output marker R2(which represent pve of marker)? 
Many reviewers ask us to provide marker R2 when we want to publish our results.

Best wishes,
Kun

**Comment by xiangzhou** [comment]
Because it is straightforward to compute: pve of a single marker=beta^2*2*maf*(1-maf)/var(y), where beta is the estimated marker effect size, maf is its minor allele frequency, and var(y) is the variance of phenotype.

**Comment by xiekunwhy** [comment]
Ok，thank you.
