### ISSUE TITLE
possible bug using the -mk flag?

### ISSUE THREAD

**Issue by yluo86** [genetics-statistics/GEMMA#212]
I'm trying to specify two relatedness matrix in my association study by using the -mk flag as suggested in the manual. But it gives out the following error:

`error! missing relatedness file. `

my GRM file looks like this
/dir/to/grm1.txt
/dir/to/grm2.txt

When using -k flag for each singe one of the GRM, gemma runs nicely. Any suggestions?

**Comment by pjotrp** [comment]
Check the code to see what is supposed to happen.
