### ISSUE TITLE
ERROR: Enforce failed for number of analyzed individuals equals 0. in src/param.cpp at line 2061 in ProcessCvtPhen

### ISSUE THREAD

**Issue by alioniya** [genetics-statistics/GEMMA#214]
Hello!

I am trying to run GRM with GEMMA using Binary PED File Format:
./0.98.1/bin/gemma -bfile test -gk 1 -o GRM_test

And I got this error:
ERROR: Enforce failed for number of analyzed individuals equals 0. in src/param.cpp at line 2061 in ProcessCvtPhen

I have 3377 individuals , 347000 SNPs
PED File is ok since I can run other software using this file (plink, GCTA, SNPtest). But it does nit . work with GEMMA. Could you help me with this pls?

Thank you!

**Comment by xiangzhou** [comment]
Make sure your phenotype column (6th column in fam file) contains non-missing phenotype values. Individuals with missing phenotype are not analyzed.

**Comment by alioniya** [comment]
Thank you, it has helped!

Now I have another error:
error writing file: ./output///workin_folder/GWAS_IMPUTED_DATA/PCA/GRM/GEMMA.cXX.txt
error writing log file: ./output///workin_folder/GWAS_IMPUTED_DATA/PCA/GRM/GEMMA.log.txt

I can write other files to this folder so there are no problems with rights. 
In GEMMA I assign this path /workin_folder/GWAS_IMPUTED_DATA/PCA/GRM/, but in the error message path is ./output///workin_folder/GWAS_IMPUTED_DATA/PCA/GRM/

Could you help with this please?

Thank you!
Regards,
Alyona

**Comment by nicolasalexandre21** [comment]
Hello, I am getting this same error:

ERROR: Enforce failed for number of analyzed individuals equals 0

Ive checked the dimensions of my bimbam file and the number of phenotypes which are correct. This only occurs for some jobs. I'm wondering if phenotypes that are NA should be converted to -9?

**Comment by nicolasalexandre21** [comment]
Other jobs of mine with lots of NA's in the phenotype file are running correctly:

GEMMA 0.98.3 (2020-11-28) by Xiang Zhou and team (C) 2012-2020
Reading Files ... 
## number of total individuals = 510
## number of analyzed individuals = 336
## number of covariates = 1
## number of phenotypes = 1
## number of total SNPs/var        = 28182308
## number of analyzed SNPs         = 27548501
Start Eigen-Decomposition...
pve estimate =2.34266e-07
se(pve) =0.305085

**Comment by Yukaixu666** [comment]
even though my fam file has the non-missing phenotype information at the 6th col, the error still happens, why and how to deal with it?
