### ISSUE TITLE
ERROR：number of total SNPs/var do not equal to number of analyzed SNPs

### ISSUE THREAD

**Issue by wangxuann1995** [genetics-statistics/GEMMA#215]
Sir,
    When I run gemma -bfile 548_M_sex -gk 1 -o M_kinship, the number of total SNPs/var        =   800160, but the number of analyzed SNPs         =    44487, what should I do for this error? I use PLINK to impute phenotypes and make sure that there is no missing value in phenotype.
   Thanks for ahead
    Wangxuan

**Comment by wangxuann1995** [comment]
when I add -notsnp the result are followed  ## number of analyzed SNPs         =    79221

**Comment by florianecoulmance** [comment]
Hello, 

Did you find any answer to your question ? I appear to be in a very similar case and would like to know what are the details/reasons of this low analysed SNPs number.

Floriane

**Comment by hlnicholls** [comment]
Hi @pjotrp  @wangxuann1995 and @florianecoulmance - were you able to get an answer to this? I also have the same issue, where the total number of SNPs is 8 million but the analyzed is 2 million, but the google group seems to be no longer available.
