### ISSUE TITLE
Build time test suite error in Debian package

### ISSUE THREAD

**Issue by tillea** [genetics-statistics/GEMMA#216]
Hi,
the Debian packaged version of GEMMA received a [bug report](https://bugs.debian.org/952190) about failures in the test suite (make check).  I've adde 'set -ex' to the sev_test_suite.sh script and appended the according output here.
Kind regards, Andreas.

[dev_test_suite.txt](https://github.com/genetics-statistics/GEMMA/files/4280571/dev_test_suite.txt)

**Comment by pjotrp** [comment]
Hi @tillea,

These are all rounding errors of the tests themselves. Nothing serious. I should change that test suite.

**Comment by tillea** [comment]
Hi Pjotr,
On Tue, Mar 03, 2020 at 03:36:25PM -0800, Pjotr Prins wrote:
> These are all rounding errors of the tests themselves. Nothing serious. I should change that test suite.
I guessed so.  Thanks for your investigation, Andreas.

**Comment by pjotrp** [comment]
Sorry about the delay. I think I fixed it. I'll ping you on a new release.

**Comment by nileshpatra** [comment]
@pjotrp hi, any update on a new release? Been quite sometime since the last one :D

**Comment by pjotrp** [comment]
On the list for this week.

**Comment by tillea** [comment]
Which week? ;-) :-P

**Comment by pjotrp** [comment]
New release done. I'll probably follow with another one before Xmas
