### ISSUE TITLE
Coding discrete covariates

### ISSUE THREAD

**Issue by pkothiyal** [genetics-statistics/GEMMA#217]
Hello,

I have to include categorical covariates with >2 classes (e.g., 0,1,2,3) and wanted to see if I can provide these as is and they will be treated as discrete categories instead of numeric values or if I should split them into N-1 dummy binary variables (where N is number of classes, 4 in this example). Thanks.

**Comment by xiangzhou** [comment]
Yes, you will want to use dummy variables to represent categorical covariates.

**Comment by pkothiyal** [comment]
Thanks. Closing the issue.
