### ISSUE TITLE
ERROR: Enforce failed for Problem reading FAM file (phenotypes out of range) in src/gemma_io.cpp at line 600 in ReadFile_fam

### ISSUE THREAD

**Issue by Jarod-R** [genetics-statistics/GEMMA#220]
Hi All,
I am getting the following error message while trying to run gemma 0.98.1 with the following command structure

`gemma -bfile GEMMA.1 -k relatedness.matrix.txt  -c covariates.txt -lmm 4 -o lmm.output -n 23`

I have multiple phenotypes attached to my fam file, all the same kind of data, some of which work and some of which give the following error: 

ERROR: Enforce failed for Problem reading FAM file (phenotypes out of range) in src/gemma_io.cpp at line 600 in ReadFile_fam

I have attached a fam file with phenotypes. All the columns work except the last 3. It appears that in some way the values in these columns are not compatible with gemma, but it is not clear to me how. Any help would be appreciated! I am new to this kind of work so if there is more info needed to provide support please let me know!
[MESA.first.round.fam.txt](https://github.com/genetics-statistics/GEMMA/files/4761779/MESA.first.round.fam.txt)

**Comment by Jarod-R** [comment]
I recently edited this post to give more clarifying information. If anyone on the gemma team has time for support it would be extremely helpful! Thank you :)

**Comment by pjotrp** [comment]
Take a look at the check in gemma_io.cpp around line 600. What does it say?

**Comment by Jarod-R** [comment]
I have looked previously and I do not understand what that section of the code accomplishes. 
```
while (i < p_max) {
      if (mapP2c.count(i + 1) != 0) {
        enforce_msg(ch_ptr,"Problem reading FAM file (phenotypes out of range)");
```
What is happening here? I looked above where mapP2C is defined and I do not understand what values it is even tracking.

**Comment by pluralbat** [comment]
Was this issue resolved? It looks exactly like the problem I am facing.

**Comment by pjotrp** [comment]
As it happens I am working on the PLINK format for gemma2lib. 

mapP2c keeps track of phenotype columns. map.count counts the number of elements belonging to a column (key). ch_ptr is the tokenizer reading the FAM file. Apparently they are out of whack. Adding columns to a FAM file you need to be in sync with the other PLINK data.

Gemma allows you to use a pheno file next to PLINK.
