### ISSUE TITLE
two questions on mvLMM 

### ISSUE THREAD

**Issue by arkyl** [genetics-statistics/GEMMA#221]
Hi,
Thanks much for the GEMMA package.

I was running GEMMA mvLMM on two phenotypes.
To save the time, I was running mvLMM on each individual chr in parallel. Is this gonna be a problem? The relatedness matrix was also derived from each chr for each individual chr run.

I also have a question about phenotypes that are not quantitative. For the two phenotypes I was running, they are quantitative and I followed the guidelines to regress out covariates and quantile normalize the residual. There are other interesting phenotypes but they are in either binary 0/1 or ordinal 0/1/2/3. Is there a way to use such phenotypes in GEMMA mvLMM?

Thanks very much!

Yue

**Comment by xiangzhou** [comment]
(1) no problem to run on chr in parallel. The results would be identical to running individual chr in sequence.
(2) we usually just treat binary 0/1 or ordinal as quantitative trait. For formally dealing with binary and count data, you can check the MACAU and PQLseq software packages if your sample size is small.

**Comment by xiangzhou** [comment]
Yes, to get the same results, you will need to use the same kinship matrix that is computed on all SNPs, for each chunk.

**Comment by dgarrimar** [comment]
OK great thank you!
