### ISSUE TITLE
GSL ERROR: function value is not finite in newton.c at line 88 errno 9

### ISSUE THREAD

**Issue by baigal628** [genetics-statistics/GEMMA#222]
I got this error when running:
gemma -bfile merge -k merge_matrix.cXX.txt -lmm 1 -n 2 -c Q.txt -o EarWT

GSL ERROR: function value is not finite in newton.c at line 88 errno 9

However, it works when I specify the phenotype as the 6th column(-n 1). The forms of data are exactly the same, but cannot work for the other columns. I also tried to put 7th column data in 6th column. Still getting the error.

I am attaching my merge.fam file.
Thank you for your help.

SRR5663730 SRR5663730 0 0 0 30.189 38.302 12.13 9.27 36.746 12.8 27.210
SRR5663754 SRR5663754 0 0 0 27.821 38.197 14.94 10.01 33.690 11.4 24.567
SRR5663760 SRR5663760 0 0 0 19.834 30.019 11.55 8.83 32.268 11.3 23.840
282set_CML218 282set_CML218 0 0 0 29.332 26.432 12.19 9.39 34.849 11.5 25.985
SRR5663766 SRR5663766 0 0 0 28.405 41.366 12.04 9.25 34.596 11.5 26.229
SRR5663770 SRR5663770 0 0 0 26.654 43.291 12.58 9.97 34.353 12.3 23.217
SRR5663774 SRR5663774 0 0 0 24.084 30.720 10.90 8.95 36.493 11.0 21.614
SRR5663786 SRR5663786 0 0 0 21.980 34.590 11.99 9.39 36.319 11.8 27.812
SRR5663806 SRR5663806 0 0 0 -9 -9 -9 -9 -9 -9 -9
SRR5663807 SRR5663807 0 0 0 26.051 39.808 11.25 8.94 37.084 12.5 26.696
SRR5663810 SRR5663810 0 0 0 19.820 31.139 11.11 8.19 31.607 11.3 21.539
SRR5663833 SRR5663833 0 0 0 13.894 20.401 8.49 7.01 30.395 10.2 22.562
SRR5663851 SRR5663851 0 0 0 33.106 43.580 11.83 9.79 35.188 11.6 23.977
SRR5663860 SRR5663860 0 0 0 32.455 44.889 12.62 9.47 33.725 11.5 21.949
SRR5663862 SRR5663862 0 0 0 30.356 40.607 13.00 9.64 33.063 11.3 23.064
SRR5663863 SRR5663863 0 0 0 25.953 36.155 11.17 8.78 34.281 11.6 23.809
SRR5663872 SRR5663872 0 0 0 23.682 33.405 11.65 8.97 33.715 11.0 23.860
SRR5663874 SRR5663874 0 0 0 31.701 42.960 12.09 9.22 35.036 11.3 24.435
SRR5663879 SRR5663879 0 0 0 19.629 37.002 15.14 10.42 33.633 11.5 27.426
SRR5663885 SRR5663885 0 0 0 20.410 27.607 11.76 9.05 29.504 10.2 20.180
SRR5663887 SRR5663887 0 0 0 -9 -9 -9 -9 -9 -9 -9
SRR5663899 SRR5663899 0 0 0 18.265 37.057 13.18 9.17 36.429 12.2 27.503
SRR5663906 SRR5663906 0 0 0 25.302 37.733 12.81 9.50 33.265 12.0 21.715
SRR5663910 SRR5663910 0 0 0 34.629 47.645 13.12 9.72 37.018 12.0 26.100
SRR5663920 SRR5663920 0 0 0 29.924 41.822 13.02 8.97 33.622 11.0 24.266
SRR5663924 SRR5663924 0 0 0 16.470 24.984 10.82 8.23 30.501 11.1 21.905
SRR5663927 SRR5663927 0 0 0 26.130 36.528 11.60 9.02 33.225 11.8 22.879
SRR5663940 SRR5663940 0 0 0 -9 -9 -9 -9 -9 -9 -9
SRR5663944 SRR5663944 0 0 0 26.082 36.746 10.29 8.48 36.601 12.7 26.481
SRR5663949 SRR5663949 0 0 0 26.733 38.626 13.05 9.40 35.578 12.3 24.626
SRR5663952 SRR5663952 0 0 0 18.911 28.693 11.88 8.95 32.105 11.1 22.846
SRR5663958 SRR5663958 0 0 0 22.196 33.894 10.62 8.58 36.589 11.8 27.122
SRR5663959 SRR5663959 0 0 0 16.201 24.407 10.38 8.03 30.456 10.9 21.450
SRR5663963 SRR5663963 0 0 0 24.890 34.229 14.15 10.17 30.611 11.3 17.012
SRR5663967 SRR5663967 0 0 0 38.758 48.232 12.24 9.82 36.269 11.4 25.152
SRR5663970 SRR5663970 0 0 0 19.531 29.632 13.70 9.50 27.248 10.3 21.781
SRR5663971 SRR5663971 0 0 0 16.018 23.679 10.16 8.06 29.589 10.7 22.347
SRR5663975 SRR5663975 0 0 0 18.998 26.544 12.19 8.95 30.268 10.8 22.381
SRR5663988 SRR5663988 0 0 0 25.079 32.887 13.59 9.41 30.199 10.2 22.034
SRR5663993 SRR5663993 0 0 0 27.567 36.085 11.05 8.84 33.290 10.7 22.708
SRR5664003 SRR5664003 0 0 0 -9 -9 -9 -9 -9 -9 -9
SRR5664005 SRR5664005 0 0 0 16.474 27.384 12.48 8.66 31.249 11.0 23.258
SRR5664007 SRR5664007 0 0 0 -9 -9 -9 -9 -9 -9 -9
SRR5664010 SRR5664010 0 0 0 17.743 37.805 10.47 8.30 31.530 11.0 23.407
SRR5664024 SRR5664024 0 0 0 -9 -9 -9 -9 -9 -9 -9
SRR5664028 SRR5664028 0 0 0 -9 -9 -9 -9 -9 -9 -9
SRR5664029 SRR5664029 0 0 0 -9 -9 -9 -9 -9 -9 -9
SRR5664034 SRR5664034 0 0 0 34.824 48.336 11.69 9.04 38.633 11.2 27.269
SRR5664035 SRR5664035 0 0 0 15.282 23.773 11.29 8.18 29.651 9.8 20.555
SRR5664080 SRR5664080 0 0 0 -9 -9 -9 -9 -9 -9 -9
SRR5664091 SRR5664091 0 0 0 26.822 36.688 11.08 8.92 34.184 11.3 24.444
SRR5664092 SRR5664092 0 0 0 35.509 49.579 12.92 9.72 37.888 12.3 28.177
SRR5664095 SRR5664095 0 0 0 19.279 29.088 12.43 9.02 30.936 10.3 21.864
SRR5664098 SRR5664098 0 0 0 17.930 29.800 12.14 9.16 32.466 11.8 23.400
SRR5664123 SRR5664123 0 0 0 24.691 38.667 11.69 8.83 36.669 12.3 26.687
SRR5664124 SRR5664124 0 0 0 20.236 30.771 12.34 9.59 33.579 12.0 22.966
SRR5664151 SRR5664151 0 0 0 27.904 32.135 11.50 9.16 33.831 11.5 24.821
SRR5664160 SRR5664160 0 0 0 22.919 34.450 10.61 8.69 33.032 11.4 21.387
SRR5675443 SRR5675443 0 0 0 20.144 27.736 11.30 8.69 29.023 10.5 20.118
SRR5675444 SRR5675444 0 0 0 24.157 33.110 11.42 8.11 34.401 11.2 22.392
SRR5675446 SRR5675446 0 0 0 -9 -9 -9 -9 -9 -9 -9
SRR5675448 SRR5675448 0 0 0 14.418 21.032 10.47 7.82 28.992 11.0 20.049
SRR5675450 SRR5675450 0 0 0 19.702 28.154 10.72 8.21 32.928 10.6 25.288
SRR5725629 SRR5725629 0 0 0 12.974 18.815 9.90 7.42 26.140 10.5 20.785
SRR5725630 SRR5725630 0 0 0 13.843 24.454 11.76 8.40 30.923 9.5 23.868
SRR5725631 SRR5725631 0 0 0 18.500 29.106 11.84 8.73 31.599 11.0 23.662
SRR5725632 SRR5725632 0 0 0 42.175 52.525 13.49 10.31 39.136 12.1 28.679
SRR5725633 SRR5725633 0 0 0 23.394 40.232 13.64 9.35 33.976 11.5 25.280
SRR5725634 SRR5725634 0 0 0 33.913 45.506 11.95 9.50 37.679 12.5 25.185
SRR5725635 SRR5725635 0 0 0 15.017 25.337 13.90 8.70 30.853 9.9 23.421
SRR5725636 SRR5725636 0 0 0 17.533 28.608 13.37 9.03 33.006 11.7 23.650
SRR5725639 SRR5725639 0 0 0 25.028 36.512 12.02 9.23 34.442 11.0 23.976
SRR5725640 SRR5725640 0 0 0 16.755 27.118 11.06 8.30 32.835 11.0 24.963
SRR5725641 SRR5725641 0 0 0 17.709 25.897 11.31 8.04 30.355 11.3 21.522
SRR5725644 SRR5725644 0 0 0 23.266 31.578 11.16 8.89 31.090 10.8 20.808
SRR5725645 SRR5725645 0 0 0 32.628 42.673 11.77 9.46 34.297 11.2 23.519
SRR5725646 SRR5725646 0 0 0 19.764 27.339 12.37 9.05 31.526 11.1 22.549
SRR5725647 SRR5725647 0 0 0 14.091 22.256 10.42 7.79 28.657 9.8 22.324
SRR5725651 SRR5725651 0 0 0 19.514 28.568 10.67 8.23 34.635 11.4 27.649
SRR5725652 SRR5725652 0 0 0 34.153 42.885 11.27 8.98 38.605 13.0 23.207
SRR5725653 SRR5725653 0 0 0 30.926 45.078 12.37 9.77 35.750 12.2 23.504
SRR5725654 SRR5725654 0 0 0 29.020 41.275 13.53 9.60 33.702 11.7 23.477
SRR5725655 SRR5725655 0 0 0 21.998 32.208 13.17 9.36 32.581 11.6 24.426
SRR5725656 SRR5725656 0 0 0 19.879 27.960 11.37 8.93 30.591 10.9 20.753
SRR5725657 SRR5725657 0 0 0 13.307 21.290 10.64 8.49 26.673 11.9 19.828
SRR5725658 SRR5725658 0 0 0 11.636 19.020 11.92 7.65 27.542 11.8 22.499
SRR5725659 SRR5725659 0 0 0 31.765 39.946 10.97 9.16 34.032 10.8 21.646
SRR5725662 SRR5725662 0 0 0 29.655 43.201 13.09 9.80 34.936 12.0 24.814
SRR5725663 SRR5725663 0 0 0 42.453 58.135 13.13 10.24 39.725 13.6 26.779
SRR5725665 SRR5725665 0 0 0 16.439 23.345 9.19 7.84 30.241 10.5 21.101
SRR5725666 SRR5725666 0 0 0 -9 -9 -9 -9 -9 -9 -9
SRR5725667 SRR5725667 0 0 0 19.309 31.766 10.68 8.26 34.442 11.5 25.893
SRR5725668 SRR5725668 0 0 0 15.158 28.837 12.17 8.28 35.253 11.6 26.967
SRR5725669 SRR5725669 0 0 0 23.743 34.404 12.95 9.76 32.590 11.8 23.007
SRR5725670 SRR5725670 0 0 0 26.644 36.624 11.98 9.37 37.916 11.6 27.478
SRR5725671 SRR5725671 0 0 0 19.165 26.669 10.95 8.29 31.950 11.6 21.438
SRR5725672 SRR5725672 0 0 0 19.570 29.499 11.28 8.17 34.114 11.0 23.607
SRR5725675 SRR5725675 0 0 0 33.576 44.561 13.64 10.12 32.968 10.8 20.719
SRR5725677 SRR5725677 0 0 0 29.725 44.651 12.52 9.74 36.427 13.0 27.177
SRR5725678 SRR5725678 0 0 0 14.432 20.277 11.47 7.31 30.298 10.9 23.043
SRR5725680 SRR5725680 0 0 0 22.919 35.127 12.10 9.37 34.725 12.1 24.972
SRR5725681 SRR5725681 0 0 0 13.261 15.402 10.84 9.19 21.311 11.5 16.031
SRR5725683 SRR5725683 0 0 0 17.799 26.804 10.49 8.48 29.938 10.9 20.958
SRR5725684 SRR5725684 0 0 0 17.341 24.683 10.25 8.08 31.899 11.1 22.938
SRR5725686 SRR5725686 0 0 0 16.444 27.403 12.39 8.75 33.242 11.7 22.096
SRR5725688 SRR5725688 0 0 0 15.585 23.596 11.63 9.31 26.766 11.2 21.513
SRR5725689 SRR5725689 0 0 0 15.941 27.504 10.87 9.17 25.372 11.4 17.851
SRR5725690 SRR5725690 0 0 0 13.906 21.837 10.03 8.26 28.090 11.7 20.151
SRR5725691 SRR5725691 0 0 0 13.036 19.161 9.96 7.79 29.033 11.0 20.179
SRR5725692 SRR5725692 0 0 0 13.410 21.512 9.61 7.51 29.490 11.7 23.401
SRR5725693 SRR5725693 0 0 0 30.572 42.978 11.90 9.55 35.022 12.0 24.871
SRR5725694 SRR5725694 0 0 0 17.045 26.333 13.42 9.36 29.291 10.6 22.800
SRR5725695 SRR5725695 0 0 0 26.006 37.321 12.13 9.00 33.482 11.3 24.467
SRR5725696 SRR5725696 0 0 0 -9 -9 -9 -9 -9 -9 -9
SRR5725697 SRR5725697 0 0 0 23.023 34.500 12.92 9.26 32.681 11.6 22.755
SRR5725698 SRR5725698 0 0 0 -9 -9 -9 -9 -9 -9 -9
SRR5725699 SRR5725699 0 0 0 25.806 34.536 10.32 8.05 34.222 11.8 23.041
SRR5725707 SRR5725707 0 0 0 30.879 40.034 11.36 9.02 35.185 11.1 22.941
SRR5725708 SRR5725708 0 0 0 20.901 28.991 13.01 9.24 31.931 10.5 23.761
SRR5725712 SRR5725712 0 0 0 18.006 31.267 12.68 8.63 33.000 11.5 24.909
SRR5725713 SRR5725713 0 0 0 28.946 41.401 12.22 8.94 37.104 12.1 26.522
SRR5725714 SRR5725714 0 0 0 18.132 28.541 10.47 8.05 32.163 11.5 23.177
SRR5725716 SRR5725716 0 0 0 28.724 42.350 11.82 8.75 38.687 11.9 30.275
SRR5725717 SRR5725717 0 0 0 16.650 26.101 11.67 9.18 31.667 11.0 23.570
SRR5725718 SRR5725718 0 0 0 -9 -9 -9 -9 -9 -9 -9
SRR5725719 SRR5725719 0 0 0 18.962 27.635 12.33 8.65 30.666 10.6 21.391
SRR5725720 SRR5725720 0 0 0 22.959 38.539 12.66 9.60 37.169 10.9 28.900
SRR5725721 SRR5725721 0 0 0 22.628 34.900 12.31 9.22 33.420 11.7 24.041
SRR5725722 SRR5725722 0 0 0 -9 -9 -9 -9 -9 -9 -9
SRR5725723 SRR5725723 0 0 0 14.824 27.069 12.55 7.94 30.183 11.0 23.248
SRR5725724 SRR5725724 0 0 0 33.017 40.279 11.91 9.03 37.195 12.0 26.752
SRR5725725 SRR5725725 0 0 0 17.517 26.785 13.07 9.23 30.999 11.6 22.437
SRR5725726 SRR5725726 0 0 0 17.702 32.334 11.31 7.98 32.186 10.9 24.065
SRR5725727 SRR5725727 0 0 0 29.594 41.566 12.17 9.53 36.198 11.8 25.287
SRR5725728 SRR5725728 0 0 0 -9 -9 -9 -9 -9 -9 -9
SRR5725731 SRR5725731 0 0 0 -9 -9 -9 -9 -9 -9 -9
SRR5725732 SRR5725732 0 0 0 15.738 23.951 12.52 9.20 27.825 11.3 19.778
SRR5725734 SRR5725734 0 0 0 24.457 37.564 12.58 9.36 34.778 12.0 25.823
SRR5725735 SRR5725735 0 0 0 27.706 40.815 12.68 9.83 34.855 11.5 25.938
SRR5725738 SRR5725738 0 0 0 22.553 35.601 11.21 8.63 35.493 11.8 28.293
SRR5725743 SRR5725743 0 0 0 21.143 35.389 13.17 8.46 34.728 11.8 25.606
SRR5725745 SRR5725745 0 0 0 -9 -9 -9 -9 -9 -9 -9
SRR5725746 SRR5725746 0 0 0 24.924 30.343 10.68 8.67 35.894 11.9 24.950
SRR5725747 SRR5725747 0 0 0 22.801 34.107 11.46 9.03 34.175 11.1 25.199
SRR5725748 SRR5725748 0 0 0 15.524 22.714 11.36 8.27 28.565 10.0 21.920
SRR5725749 SRR5725749 0 0 0 12.987 22.747 11.41 7.28 32.024 11.0 24.400
SRR5725751 SRR5725751 0 0 0 27.401 35.192 11.14 8.79 36.857 11.3 24.174
SRR5725752 SRR5725752 0 0 0 -9 -9 -9 -9 -9 -9 -9
SRR5725753 SRR5725753 0 0 0 -9 -9 -9 -9 -9 -9 -9
SRR5725754 SRR5725754 0 0 0 25.401 33.178 11.90 8.78 32.037 11.0 23.173
SRR5725755 SRR5725755 0 0 0 22.801 31.966 13.46 9.45 29.743 10.4 20.322
SRR5725756 SRR5725756 0 0 0 17.693 24.484 10.75 8.66 27.947 10.9 20.696
SRR5725757 SRR5725757 0 0 0 21.274 35.103 9.82 8.14 37.504 11.7 24.999
SRR5725761 SRR5725761 0 0 0 22.197 30.976 11.31 8.80 34.053 11.8 23.503
SRR5725762 SRR5725762 0 0 0 19.590 30.148 13.13 9.53 32.823 11.0 24.743
SRR5725763 SRR5725763 0 0 0 19.585 30.182 11.43 8.84 34.873 11.4 24.900
SRR5725764 SRR5725764 0 0 0 20.151 30.409 12.13 8.47 32.262 10.4 23.555
SRR5725765 SRR5725765 0 0 0 27.459 35.767 13.40 9.76 32.494 11.0 20.722
SRR5725766 SRR5725766 0 0 0 30.583 33.547 13.32 9.64 31.337 10.8 21.986
SRR5725769 SRR5725769 0 0 0 15.611 18.050 10.41 7.86 29.919 11.0 25.298
SRR5725770 SRR5725770 0 0 0 16.286 19.043 9.25 7.95 31.770 11.1 23.434
SRR5725773 SRR5725773 0 0 0 17.606 29.074 15.92 11.26 30.220 10.8 21.938
SRR5725776 SRR5725776 0 0 0 19.167 31.326 11.40 8.66 36.432 12.1 27.903
SRR5725779 SRR5725779 0 0 0 -9 -9 -9 -9 -9 -9 -9
SRR5725780 SRR5725780 0 0 0 37.464 51.785 14.52 10.99 35.497 12.5 25.046
SRR5725781 SRR5725781 0 0 0 30.723 41.399 10.76 9.29 35.864 11.6 25.979
SRR5725782 SRR5725782 0 0 0 27.355 38.134 10.90 8.69 35.007 12.1 24.577
SRR5725783 SRR5725783 0 0 0 31.543 45.329 12.84 9.79 36.860 11.7 25.818
SRR5725784 SRR5725784 0 0 0 -9 -9 -9 -9 -9 -9 -9
SRR5725785 SRR5725785 0 0 0 16.602 25.311 11.45 7.79 31.069 10.1 24.939
SRR5725787 SRR5725787 0 0 0 27.212 38.615 12.24 9.44 34.040 11.0 24.787
SRR5725788 SRR5725788 0 0 0 34.442 46.547 13.02 9.92 35.312 11.0 24.354
SRR5725791 SRR5725791 0 0 0 25.597 27.716 10.96 8.80 36.985 12.0 26.134
SRR5725792 SRR5725792 0 0 0 15.230 22.593 9.92 7.27 29.761 9.6 21.562
SRR5725793 SRR5725793 0 0 0 21.875 29.282 10.57 7.91 34.996 10.7 24.978
SRR5725794 SRR5725794 0 0 0 18.940 27.596 10.67 8.30 33.697 11.3 25.105
SRR5725795 SRR5725795 0 0 0 13.400 19.155 9.08 7.58 30.272 10.4 22.964
SRR5725796 SRR5725796 0 0 0 24.313 33.964 11.18 8.78 33.662 11.7 22.591
SRR5725797 SRR5725797 0 0 0 24.482 36.820 14.99 10.42 33.126 11.3 22.358
SRR5725802 SRR5725802 0 0 0 14.688 21.008 9.39 7.93 30.590 10.6 21.362
SRR5725803 SRR5725803 0 0 0 22.521 35.784 13.51 9.75 34.805 11.5 20.497
SRR5725804 SRR5725804 0 0 0 29.895 40.461 12.09 9.11 34.447 11.5 23.400
SRR5725805 SRR5725805 0 0 0 23.011 32.967 10.91 8.63 33.269 11.3 24.171
SRR5725806 SRR5725806 0 0 0 30.144 42.504 12.29 9.27 36.368 11.3 25.410
SRR5725811 SRR5725811 0 0 0 29.484 51.580 13.26 9.16 36.061 12.3 25.323
SRR5725812 SRR5725812 0 0 0 -9 -9 -9 -9 -9 -9 -9
SRR5725813 SRR5725813 0 0 0 24.291 34.586 11.14 9.21 33.996 11.9 23.466
SRR5725814 SRR5725814 0 0 0 20.530 28.921 10.42 8.38 31.552 11.0 21.600
SRR5725815 SRR5725815 0 0 0 14.379 21.747 11.61 8.17 28.267 10.5 20.992
SRR5725816 SRR5725816 0 0 0 16.989 26.053 11.11 8.49 32.713 11.0 25.545
SRR5725820 SRR5725820 0 0 0 27.801 36.866 11.82 9.27 36.193 11.9 23.535
SRR5725821 SRR5725821 0 0 0 30.885 41.993 13.46 10.03 36.174 12.5 25.095
SRR5725822 SRR5725822 0 0 0 14.060 20.088 11.88 8.13 29.642 11.5 22.535
SRR5725825 SRR5725825 0 0 0 17.648 24.229 8.14 7.60 31.301 11.1 21.939
SRR5725828 SRR5725828 0 0 0 30.682 40.952 12.27 8.98 35.535 12.2 24.438
SRR5725829 SRR5725829 0 0 0 21.158 29.205 10.62 8.60 30.947 11.8 20.768
SRR5725830 SRR5725830 0 0 0 34.126 47.130 11.12 9.49 38.499 12.8 25.864
SRR5725831 SRR5725831 0 0 0 -9 -9 -9 -9 -9 -9 -9
SRR5725834 SRR5725834 0 0 0 18.421 30.821 12.88 9.11 32.108 11.0 24.469
SRR5725835 SRR5725835 0 0 0 -9 -9 -9 -9 -9 -9 -9
SRR5725836 SRR5725836 0 0 0 19.650 26.911 9.64 7.86 32.525 11.7 22.658
SRR5725837 SRR5725837 0 0 0 -9 -9 -9 -9 -9 -9 -9
SRR5725838 SRR5725838 0 0 0 27.720 49.929 12.34 9.41 37.602 11.5 27.156
SRR5725841 SRR5725841 0 0 0 24.699 34.693 12.04 9.55 32.967 10.8 25.897
SRR5725844 SRR5725844 0 0 0 29.282 41.048 11.65 8.80 38.466 12.0 27.379
SRR5725845 SRR5725845 0 0 0 21.590 32.887 10.47 8.77 33.803 10.8 25.383
SRR5725846 SRR5725846 0 0 0 -9 -9 -9 -9 -9 -9 -9
SRR5725847 SRR5725847 0 0 0 18.934 29.564 12.62 9.14 31.653 10.6 21.978
SRR5725848 SRR5725848 0 0 0 16.454 25.230 11.03 7.29 31.853 11.5 24.423
SRR5725849 SRR5725849 0 0 0 26.851 39.175 11.58 9.16 34.194 12.1 22.889
SRR5725850 SRR5725850 0 0 0 29.831 42.178 12.08 9.28 37.827 11.9 25.579
SRR5725853 SRR5725853 0 0 0 28.502 42.468 12.62 9.59 33.942 11.8 24.562
SRR5725855 SRR5725855 0 0 0 27.990 38.302 13.41 10.29 34.890 11.6 24.596
SRR5725856 SRR5725856 0 0 0 -9 -9 -9 -9 -9 -9 -9
SRR5725857 SRR5725857 0 0 0 16.345 23.721 9.83 7.88 31.222 11.0 21.193
SRR5725859 SRR5725859 0 0 0 15.396 25.137 11.99 8.69 31.271 11.0 23.718
SRR5725861 SRR5725861 0 0 0 19.598 27.503 10.86 8.69 28.680 11.3 18.981
SRR5725862 SRR5725862 0 0 0 40.163 53.063 12.52 9.97 36.189 12.3 23.286
SRR5725864 SRR5725864 0 0 0 18.726 29.047 10.29 8.02 33.617 11.4 23.591
SRR5725865 SRR5725865 0 0 0 23.752 31.182 12.46 8.66 32.063 10.8 21.648
SRR5725870 SRR5725870 0 0 0 22.997 30.775 11.24 9.11 32.715 10.9 21.845
SRR5725871 SRR5725871 0 0 0 -9 -9 -9 -9 -9 -9 -9
SRR5725872 SRR5725872 0 0 0 11.020 20.021 12.97 7.69 29.849 11.0 22.453
SRR5725873 SRR5725873 0 0 0 17.003 28.026 12.91 9.16 30.227 11.3 22.762
SRR5725874 SRR5725874 0 0 0 -9 -9 -9 -9 -9 -9 -9
SRR5725875 SRR5725875 0 0 0 17.462 27.155 11.01 8.16 32.466 11.8 23.962
SRR5725876 SRR5725876 0 0 0 29.631 40.071 12.97 9.86 32.724 11.0 22.798
SRR5725880 SRR5725880 0 0 0 -9 -9 -9 -9 -9 -9 -9
SRR5725881 SRR5725881 0 0 0 18.098 25.525 9.31 7.20 32.965 11.2 23.909
SRR5725882 SRR5725882 0 0 0 22.771 39.014 12.17 8.69 39.739 12.4 29.112
SRR5725883 SRR5725883 0 0 0 28.133 39.468 13.75 9.63 34.074 12.2 22.330
SRR5725884 SRR5725884 0 0 0 18.952 26.535 9.19 7.99 33.439 11.7 23.546
SRR5725885 SRR5725885 0 0 0 23.442 35.343 12.91 9.64 32.231 11.3 23.026
SRR5725887 SRR5725887 0 0 0 30.574 38.641 11.56 9.26 34.047 10.9 22.563
SRR5725889 SRR5725889 0 0 0 14.989 27.575 15.53 9.27 28.864 10.3 23.102
SRR5725890 SRR5725890 0 0 0 -9 -9 -9 -9 -9 -9 -9
SRR5725891 SRR5725891 0 0 0 25.599 38.498 10.93 9.44 36.699 11.7 25.757
SRR5725892 SRR5725892 0 0 0 26.195 39.285 13.99 9.94 34.762 12.0 24.298
SRR5725893 SRR5725893 0 0 0 22.012 36.110 14.25 9.08 34.381 11.2 25.827
SRR5725894 SRR5725894 0 0 0 18.852 30.098 12.07 8.99 31.835 10.8 22.550
SRR5725896 SRR5725896 0 0 0 32.236 47.347 12.60 9.57 38.212 12.8 27.262
SRR5725898 SRR5725898 0 0 0 24.523 33.801 11.92 9.03 35.837 11.4 25.068
SRR5725899 SRR5725899 0 0 0 27.217 37.640 10.85 9.31 34.585 12.0 22.538
SRR5725900 SRR5725900 0 0 0 22.170 31.360 10.50 8.47 34.687 11.7 25.684
SRR5725901 SRR5725901 0 0 0 24.443 34.780 12.57 9.24 31.823 11.6 22.332
SRR5725902 SRR5725902 0 0 0 28.117 39.721 11.53 9.27 35.260 12.2 25.347
SRR5725903 SRR5725903 0 0 0 30.684 40.646 11.48 9.46 34.198 11.7 25.060
SRR5725904 SRR5725904 0 0 0 19.290 30.829 11.69 8.27 31.033 10.5 21.385
SRR5725905 SRR5725905 0 0 0 16.146 24.528 11.34 8.27 31.625 11.0 21.775
SRR5725906 SRR5725906 0 0 0 18.024 28.574 12.04 8.41 33.633 11.3 26.472
SRR5725907 SRR5725907 0 0 0 25.035 35.525 12.49 9.47 32.471 11.7 19.896
SRR5725908 SRR5725908 0 0 0 -9 -9 -9 -9 -9 -9 -9
SRR5725909 SRR5725909 0 0 0 -9 -9 -9 -9 -9 -9 -9
SRR5725913 SRR5725913 0 0 0 -9 -9 -9 -9 -9 -9 -9
SRR5725915 SRR5725915 0 0 0 25.242 34.263 14.85 9.99 29.244 10.2 18.721
SRR5725918 SRR5725918 0 0 0 43.949 55.787 13.99 10.79 36.286 11.3 23.463
SRR5725919 SRR5725919 0 0 0 -9 -9 -9 -9 -9 -9 -9
SRR5725920 SRR5725920 0 0 0 -9 -9 -9 -9 -9 -9 -9
SRR5725921 SRR5725921 0 0 0 22.382 32.451 12.93 10.16 32.942 12.0 22.775
SRR5725922 SRR5725922 0 0 0 19.552 29.125 12.62 8.97 31.060 10.4 22.735
SRR5725924 SRR5725924 0 0 0 17.473 27.435 10.12 7.86 33.151 11.4 24.923
SRR5725928 SRR5725928 0 0 0 -9 -9 -9 -9 -9 -9 -9
SRR5725930 SRR5725930 0 0 0 23.427 32.597 12.43 9.61 31.770 10.5 21.440

**Comment by xiangzhou** [comment]
If you place the 7th column data in 6th column and analyze the 6th column but still receive the same error, then it suggests that the 7th column outcome data is causing the error. Have you tried to quantile normalize (a.k.a. inverse normalize) the 7th column data?

**Comment by baigal628** [comment]
I used BLUP to obtain phenotypic data. Histograms show roughly normal. I didn't use quantile normalization.

**Comment by jenny315** [comment]
Hi, I have the same problem
 
When run
```
gemma -bfile gwas_data -k output/Gemm.sXX.txt -lmm 1 -n 4 -o sex
```

log:
```......
Reading Files ...
## number of total individuals = 19
## number of analyzed individuals = 19
## number of covariates = 1
## number of phenotypes = 1
## number of total SNPs = 19464101
## number of analyzed SNPs = 13387718
Start Eigen-Decomposition...
pve estimate =0.99999
se(pve) =0.00396103
gsl: newton.c:88: ERROR: function value is not finite           3.08%
Default GSL error handler invoked.
Aborted (core dumped)
```
fam file like this

```
G101 G101 0 0 2 F F9 2 0 1
G136 G136 0 0 2 F F5 2 0 1
G148 G148 0 0 1 M M1 1 1 0
G163 G163 0 0 2 F F2 2 0 1
G181 G181 0 0 1 M M7 1 1 0
G21 G21 0 0 2 F F10 2 0 1
G238 G238 0 0 1 M M5 1 1 0
G267 G267 0 0 2 F F7 2 0 1
G294 G294 0 0 1 M M6 1 1 0
G297 G297 0 0 2 F F3 2 0 1
G301 G301 0 0 1 M M8 1 1 0
G315 G315 0 0 2 F F1 2 0 1
G355 G355 0 0 1 M M3 1 1 0
G360 G360 0 0 2 F F11 2 0 1
G375 G375 0 0 1 M M2 1 1 0
G41 G41 0 0 2 F F6 2 0 1
G54 G54 0 0 2 F F8 2 0 1
G63 G63 0 0 1 M M4 1 1 0
G68 G68 0 0 2 F F4 2 0 1
```
