### ISSUE TITLE
Generating Kinship Matrix

### ISSUE THREAD

**Issue by baigal628** [genetics-statistics/GEMMA#223]
I have a question about generating a kinship matrix. When I use the Plink format data to generate the K matrix, I think the algorithm only used the 6th column in .fam file. Does it mean we can only use this matrix for estimating phenotypes in the 6th column? So do we need to regenerate the individual k matrix for different phenotypic data?

**Comment by xiangzhou** [comment]
The algorithm only uses the 6th column in .fam file to determine which individual has non-missing phenotype so that should be included to compute the K matrix. Therefore, it does not use the actual phenotype values to compute K. And there is no need to regenerate K for different phenotype data.

**Comment by baigal628** [comment]
Thanks!
