### ISSUE TITLE
after 72 hours running, there was no output results

### ISSUE THREAD

**Issue by xiaoxihe** [genetics-statistics/GEMMA#224]
Here's my command:
`nohup ./gemma-0.98.1-linux-static -bfile hcp_impute2_qc -k kin_gk2.sXX.txt -n 1 -c hcp_20covar.txt -lmm 1 -o L_C_Thck_GWAS -debug > L_C_Thck.file 2>&1 &`

The process looks normal:
![image](https://user-images.githubusercontent.com/49421269/83861493-3c0f9600-a753-11ea-8b06-ff362f82d065.png)

Of course, I omitted the other rows from 1-100.

![image](https://user-images.githubusercontent.com/49421269/83861843-b17b6680-a753-11ea-9ca3-ffc8a2a96c85.png)

And there was no result in out file.

I ran 4 gemma at the same time. Two results were no problem. The process looks like this:

![image](https://user-images.githubusercontent.com/49421269/83862206-34042600-a754-11ea-8003-a4d7c605fb0d.png)

I want to know why? 72 hours is too long! I'm in a hurry. Wait online.

**Comment by xiangzhou** [comment]
This is likely because there are too many covariates and the algorithm failed to converge on one of the last SNPs. Have you tried to remove covariate effects first and use phenotype residual for analysis?

**Comment by pjotrp** [comment]
Also look for highly correlated phenotypes and covariates

**Comment by xiaoxihe** [comment]
Thank you!
