### ISSUE TITLE
Including -gxe produces error: GSL ERROR: function value is not finite in brent.c at line 58 errno 9

### ISSUE THREAD

**Issue by DeWitP** [genetics-statistics/GEMMA#225]
Hi! Thanks for nice software! I am trying to run GEMMA with the -gxe option. Without the option, the software runs fine, but when I include the -gxe option I get the rror: "GSL ERROR: function value is not finite in brent.c at line 58 errno 9"

I cannot find any information on the formatting of the gxe file, so perhaps my file is wrongly formatted. The GEMMA manual only states: "This gxe file contains a column of environmental variables" so I only include one column of an environmental factor (salinity in my case) in the file, in the same order as the samples are listed in the .fam file (see attached). Do I need to include something more? Thanks!

[S_gxe.txt](https://github.com/genetics-statistics/GEMMA/files/4791780/S_gxe.txt)

**Comment by DeWitP** [comment]
Hi again, nevermind. I added also the sample names in the gxe file and it worked. You might want to clarify this in the manual though. 
All the best, Pierre

**Comment by pjotrp** [comment]
You can send a pull request. That would be appreciated!
