### ISSUE TITLE
mvLMM results in exactly zero (0.000000e+00) p-values

### ISSUE THREAD

**Issue by dgarrimar** [genetics-statistics/GEMMA#226]
mvLMM of GEMMA 0.98.1 (`gemma -lmm -g geno.txt -k kinship.sXX.txt -p pheno.txt -n 1 2 3 -outdir . -o outfile`) results in p-values that are **_exactly 0_** (`0.000000e+00`) for SNPs that are not associated with the phenotypes. When looking at these SNPs resulting in these p-values, I found always the same pattern of genotype counts:

```bash
snp1
      2  0
     16  1
     82  2
snp2
      2  0
     31  1
     67  2
snp3 
     20  1
     80  2
```

When running gemma for a single 0-p-value SNP, however (i.e. `geno.txt` with just one line) the p-value is correct. 

It seems that in these cases the ALT allele has much larger counts than the REF allele. Still this does not always happen, as the following variants result in normal p-values (maybe the previous are more unbalanced...):

```
snpA
     41  0
     59  1
snpB
     33  0
     16  1
     51  2
```

**Comment by pjotrp** [comment]
If we can reproduce this problem we may be able to fix it. I'll close the issue until we get an example.
