### ISSUE TITLE
GSL ERROR

### ISSUE THREAD

**Issue by voichek** [genetics-statistics/GEMMA#227]
Dear GEMMA team,

I am getting the following error:
```
GEMMA 0.98.1 (2018-12-10) by Xiang Zhou and team (C) 2012-2018
Reading Files ... 
## number of total individuals = 24
## number of analyzed individuals = 24
## number of covariates = 1
## number of phenotypes = 1
## number of total SNPs/var        =    10001
## number of analyzed SNPs         =    10001
Start Eigen-Decomposition...
pve estimate =3.94443e-06
se(pve) =0.224448
GSL ERROR: function value is not finite in brent.c at line 202 errno 9
```

I tried to run it also with version 0.96 and got a similar error:
```
gsl: brent.c:57: ERROR: function value is not finite            0.00%

Default GSL error handler invoked.

Aborted
```

All the files used to run this are pretty small and I can share them by mail.

Thanks in advance,
Yoav Voichek

**Comment by voichek** [comment]
The SNPs pattern in the population seem to be very redundant, that is having similar information. Can this lead to this problem?

**Comment by xiangzhou** [comment]
This is likely due to the small sample size. Normalizing the phenotype properly may help. We typically use quantile normalization for phenotypes.
