### ISSUE TITLE
GSL ERROR: matrix is singular in lu.c at line 262 errno 1 mvLMM 19 phenotypes

### ISSUE THREAD

**Issue by TeaByrd** [genetics-statistics/GEMMA#229]
Hey guys, 

I'm receiving this popular GSL Error:

"GSL ERROR: matrix is singular in lu.c at line 262 errno 1"

I'm executing a very big multivariate linear mixed model with 19 outcomes, 6 Covariates (+ Intercept) and only 106 samples:

GEMMA 0.98.1 (2018-12-10) by Xiang Zhou and team (C) 2012-2018
Reading Files ... 
## number of analyzed SNPs         =     6780
Start Eigen-Decomposition...

Both my phenotypes and covariates are pretty much uncorrelated (to themselves and to each other). Furthermore, all my phenotypes are quantile normalized and covariates are scaled.
Strangely, I'm not getting the error, when I execute the same thing with only 5 covariates (4 + intercept).

I know, my sample size is super small and I'm using a lot of phenotypes. So I'm asking, if anyone can suggest me what to do to get results with all my covariates? Should I split the phenotypes and build multiple smaller mvLMM? Or is this maybe due to my number of total SNPs I'm using?

The whole output file is attached. 
[gemma_output.txt](https://github.com/genetics-statistics/GEMMA/files/4931388/gemma_output.txt)

Best regards and thanks in advance,

Thomas

**Comment by xiangzhou** [comment]
There are approximately d^2 parameters for d phenotypes in the mvLMM, and you will need dozens of samples to estimate each parameter. So you will need at least 20*d^2 samples to analyze d phenotypes. In your case, you will need at least 10,000 samples to analyze 19 traits. Otherwise, you will see algorithmic errors.
