### ISSUE TITLE
-lopenblas library not found

### ISSUE THREAD

**Issue by Marisa89** [genetics-statistics/GEMMA#230]
Good afternoon, 
I am trying to install GEMMA in two different MacBook Pro. I am having problems with the installation:

c++ -I/usr/local/opt/openblas/include -DOPENBLAS -isystem/usr/local/opt/openblas/include -DNDEBUG -O3 -DHAVE_INLINE -pthread -Wall -std=gnu++11   -isystem/usr/local/include/eigen3 -Icontrib/catch-1.9.7 -Isrc src/bslmm.o src/bslmmdap.o src/debug.o src/eigenlib.o src/fastblas.o src/gemma.o src/gemma_io.o src/gzstream.o src/lapack.o src/ldr.o src/lm.o src/lmm.o src/logistic.o src/main.o src/mathfunc.o src/mvlmm.o src/param.o src/prdt.o src/varcov.o src/vc.o -lgsl -lz -lopenblas -o ./bin/gemma
ld: library not found for -lopenblas
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bin/gemma] Error 1

I have openblas 0.3.10 an lapack 3.9.0

Any help is welcome. I have been trying to install it for two days with no success.

Thanks in advance

**Comment by pjotrp** [comment]
Did you try the conda install on MacOS? Or use the provided binary in a Linux VM on MacOS. Both routes should work. In a future version we may provide a Docker container, but it is not the case yet.

**Comment by pjotrp** [comment]
I opened #160

**Comment by pjotrp** [comment]
@Marisa89 any success? If you want we can to create a Docker container for you to run/test.

**Comment by pjotrp** [comment]
I have created a Docker container that may run on MacOS:

http://ipfs.genenetwork.org/ipfs/QmXzsnU5BRLWe57GR2foiV2y5Uuy9mRPipUwLYdEFbisYV
