### ISSUE TITLE
Difficulties in understanding mvLMM output 

### ISSUE THREAD

**Issue by shafiqnoa** [genetics-statistics/GEMMA#236]
I ran mvLMM for two traits (x and y) adjusting for four additional traits (including the intercept).
However, I can not distinguish which one is the estimate for genetic correlation between x and y.  

here is the log:
##
##
##
##
## REMLE estimate for Vg in the null model: 
0.69833
0.0375916	0.065652
## se(Vg): 
0.0321777
0.0108328	0.0072974
## REMLE estimate for Ve in the null model: 
0.273633
-0.00751629	0.120799
## se(Ve): 
0.0184782
0.00813352	0.00677273
## MLE estimate for Vg in the null model: 
0.69775	0.0375614
0.0375614	0.0655758
## se(Vg): 
0.0321219
0.0108154	0.00728674
## MLE estimate for Ve in the null model: 
0.273107	      -0.00751642
-0.00751642	0.120644
## se(Ve): 
0.018433
0.008118	0.0067622
## estimate for B (d by c) in the null model (columns correspond to the covariates provided in the file): 
0.0940317	-0.0878004	0.166091	        -0.0150725
0.406611 	-0.120677	0.0680489	-0.0198323
## se(B): 
0.0752651	0.0684905	0.0199194	0.0139538
0.0320747	0.0288643	0.00833621	0.00586676
##
##      time on optimization = 18.718 min 
##

**Comment by xiangzhou** [comment]
Vg is the genetic covariance. You can obtain genetic correlation based on this covariance estimate.
