### ISSUE TITLE
Debian bug fails unit test

### ISSUE THREAD

**Issue by pjotrp** [genetics-statistics/GEMMA#242]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=982692

**Comment by pjotrp** [comment]
I need to change the testing approach. These minor round-off problems are going to show up on different architectures.

**Comment by emollier** [comment]
Not sure if that helps, but Lucas Nussbaum published another build result in the Debian Bug#982692 a dozen of minutes ago.
