### ISSUE TITLE
The gemma model choose problem

### ISSUE THREAD

**Issue by K-zhangfengwei** [genetics-statistics/GEMMA#253]
I perform GWAS analysis of **quality traits, coat color.**
Very good results and now i write the paper.
The command I ran is as follows:

```
gemma-0.98.1-linux-static -bfile 00_population/06_plink_maf0.05/97 -p BO.txt -gk 2 -o BO
cp output/BO.sXX.txt ./
gemma-0.98.1-linux-static -bfile 00_population/06_plink_maf0.05/97 -k BO.sXX.txt -p BO.txt -lmm 1 -n 1 -o BO
```

why i  need produce the **-K  flie**?  How to understand it?
and Is this method correct?

**Comment by pjotrp** [comment]
K is for kinship or GRM. It is in the original paper.
