### ISSUE TITLE
Errors when running GEMMA in an SoS step but ok in command line

### ISSUE THREAD

**Issue by zhangbs92** [genetics-statistics/GEMMA#258]
**Describe the bug**
ERROR: Enforce failed for file_kin /home/bz2437/UKB_genotype_data/fam_folder/output/ascertain_fam_1.cXX.txt: open file in src/param.cpp at line 905 in CheckParam

**To Reproduce**

**Expected behavior**

**Screenshots**

I tried to call gemma in one step of my SoS code. In dryrun mode, my sos code works fine:

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/67199679/133481517-82bd700f-b050-4799-ae3b-340f49345839.png">

Even I copied and paste the command lines and ran it in terminal, it worked perfectly:

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/67199679/133481714-7d8b92eb-ba87-4c86-bbcb-90fbded3a777.png">

<img width="1065" alt="image" src="https://user-images.githubusercontent.com/67199679/133481771-7125800f-85bd-45f5-a73f-8272d5544200.png">

However, when I run the whole SoS workflow, I saw errors like this:

<img width="1066" alt="image" src="https://user-images.githubusercontent.com/67199679/133481913-29e03a24-d19c-4b63-b98a-bf1f5c50f4b8.png">

 Does anyone know what the problem is?

Thanks,
Bingsong

**Additional context**

### Check list:

1. [X] I have found an issue with GEMMA
2. [ ] I have searched for it on the [issue tracker](https://github.com/genetics-statistics/GEMMA/issues?q=is%3Aissue) (incl. closed issues)
3. [ ] I have searched for it on the [mailing list](https://groups.google.com/forum/#!forum/gemma-discussion)
4. [ ] I have tried the latest [release](https://github.com/genetics-statistics/GEMMA/releases) of GEMMA
5. [ ] I have read and agreed to below code of conduct
6. [ ] If it is a support/install question I have posted it to the [mailing list](https://groups.google.com/forum/#!forum/gemma-discussion)
7. [ ] If it is software development related I have posted a new issue on the [issue tracker](https://github.com/genetics-statistics/GEMMA/issues) or added to an existing one
8. [ ] In the message I have included the output of my GEMMA run
9. [ ] In the message I have included the relevant .log.txt file in the output directory
10. [ ] I have made available the data to reproduce the problem (optional)

To find bugs the GEMMA software developers may ask to install a
development version of the software. They may also ask you for your
data and will treat it confidentially.  Please always remember that
GEMMA is written and maintained by volunteers with good
intentions. Our time is valuable too. By helping us as much as
possible we can provide this tool for everyone to use.

**Comment by pjotrp** [comment]
Are your nodes trying to open the same file? Make sure they are uniquely named, such as gemma-wrapper does.
