### ISSUE TITLE
"-gxe" not working

### ISSUE THREAD

**Issue by tcarv** [genetics-statistics/GEMMA#27]
Hi Xiang,

Any time I try to run GEMMA with the "-gxe" option it gives me the following error:

Start Eigen-Decomposition...
pve estimate =0.130578
se(pve) =0.195554
gsl: brent.c:202: ERROR: function value is not finite           0.00%
Default GSL error handler invoked.
Segmentation fault (core dumped)

The only way it seems to run is if all the values in the "-gxe" file are 0. 
Is this issue specific to me?

Thanks

**Comment by pjotrp** [comment]
Eigen segfault. If you are linking against OpenBLAS this could be the same issue as https://github.com/xianyi/OpenBLAS/issues/703. Upgrade OpenBLAS to latest.

**Comment by pcarbo** [comment]
@tcarv Could you please provide the full `gemma` command that you tried to run?
