### ISSUE TITLE
GEMMA for UK Biobank genome-wide analysis?

### ISSUE THREAD

**Issue by jielab** [genetics-statistics/GEMMA#283]
Dear Dr. Zhou and colleagues:

**Can we use GEMMA to run a GWAS on UK Biobank data**?

I understand that I shall run each chromosome separately.
But still, if GEMMA only takes plink bed/bim/fam format data, the UK Biobank data might be too big. As you know, **the UK Biobank imputed genetic data is originally in .bgen format. I then converted them to .pgen format**, which stores the imputed dosage. 

Also, is it possible to **use GEMMA to calculate kinship for the UK Biobank data?** I guess the kinship matrix would be too big to be made, too big to be stored, too big to be used.

If GEMMA could actually run GWAS on the UK Biobank data (for example, for height), can you please kindly throw an example script here?

Thanks!

Jie

**Comment by Yukaixu666** [comment]
helllo, I am using the GEMMA to conducted GWAS based on LMM using the imputed data from UKB, also, I encount some question! especially, when I try to calculated kinship matrix, the software tells ERROR: Enforce failed for number of analyzed individuals equals 0. in src/param.cpp at line 2061 in ProcessCvtPhen, even though my fam files have the phenotype information at the 6th column, I dont konw what happened?

**Comment by pjotrp** [comment]
I don't think gemma is particularly suited to >1K individuals right now. We are working on a larger gemma.
