### ISSUE TITLE
relatedness matrix

### ISSUE THREAD

**Issue by liaguiro** [genetics-statistics/GEMMA#285]
Hi,

I got the relatedness matrix and saw in the log that it used one phenotype. I have > 100 phenotypes. Does it mean that I need to get a relatedness matrix for each phenotype?

FYI, the link to the google group is broken. I couldn't connect to gemma's google group.

Thanks,

Lina

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, paste output to help explain your problem.

**Additional context**

### Check list:

1. [X] I have found an issue with GEMMA
2. [ ] I have searched for it on the [issue tracker](https://github.com/genetics-statistics/GEMMA/issues?q=is%3Aissue) (incl. closed issues)
3. [ ] I have searched for it on the [mailing list](https://groups.google.com/forum/#!forum/gemma-discussion)
4. [ ] I have tried the latest [release](https://github.com/genetics-statistics/GEMMA/releases) of GEMMA
5. [ ] I have read and agreed to below code of conduct
6. [ ] If it is a support/install question I have posted it to the [mailing list](https://groups.google.com/forum/#!forum/gemma-discussion)
7. [ ] If it is software development related I have posted a new issue on the [issue tracker](https://github.com/genetics-statistics/GEMMA/issues) or added to an existing one
8. [ ] In the message I have included the output of my GEMMA run
9. [ ] In the message I have included the relevant .log.txt file in the output directory
10. [ ] I have made available the data to reproduce the problem (optional)

To find bugs the GEMMA software developers may ask to install a
development version of the software. They may also ask you for your
data and will treat it confidentially.  Please always remember that
GEMMA is written and maintained by volunteers with good
intentions. Our time is valuable too. By helping us as much as
possible we can provide this tool for everyone to use.

**Comment by xiangzhou** [comment]
You only need to compute the genetic relatedness matrix once. The matrix itself is based solely on the genetic data, not the phenotype. The phenotype is only used to determine which subjects are selected for analysis. So, once you've computed the matrix for all subjects, you can reuse it for different phenotypes.
