### ISSUE TITLE
make relatedness matrix: gsl ERROR: vector length n must be positive integer 

### ISSUE THREAD

**Issue by DSLituiev** [genetics-statistics/GEMMA#29]
I am trying to figure out how to make relatedness matrix and running into an error:

```
$gemma -bfile $BASE -epm ${BASE}.out.param.txt \
        -emu ${BASE}.out.log.txt -ebv ${BASE}.out.bv.txt \
        -k ${BASE}.cXX.txt \
        -predict 1 -o ${BASE}.predicted

Reading Files ...
## number of total individuals = 94
## number of analyzed individuals = 94
## number of covariates = 1
## number of phenotypes = 1
gsl: init_source.c:29: ERROR: vector length n must be positive integer
Default GSL error handler invoked.
Segmentation fault
```

I am using pre-compiled 0.95alpha and 0.94.1 binaries on CentOS6.7.

**Comment by mkerin** [comment]
I am also hitting this error. Did you solve it in the end?

**Comment by xiangzhou** [comment]
Have you masked the individuals who you want to predict the phenotypes for? To do that, you can replace their phenotype values in the phenotype file with NA.

**Comment by mkerin** [comment]
Just thought I'd post to say that solved the problem. Thanks for the quick response!

**Comment by pcarbo** [comment]
@xiangzhou I'm labeling this as a bug because it would be good to have proper error handling---and give a more informative error message---before a segmentation fault is reached.

**Comment by pjotrp** [comment]
I am closing this issue. Yes, we should have proper error handling. But it is a largish subject. Best to keep adding enforce_msg statements etc.
