### ISSUE TITLE
Info_msg() Macro in debug.h.

### ISSUE THREAD

**Issue by yanyan420** [genetics-statistics/GEMMA#290]
Hello,

I have been trying to add gemma as a tool in my local Galaxy instance. When I ran an association analysis that finished with success, Galaxy flagged that job as failed. After finishing an analysis, gemma code prints an info message via the macro info_msg() that is defined in debug.h, that message is perceived as being printed to stderr by Galaxy and job that runs the analysis is flagged as failed by Galaxy. What solution to this would you suggest?

Thanks in advance for your response,

Rayane.

**Comment by pjotrp** [comment]
redirect stderr to stdout.
