### ISSUE TITLE
variance contribution of tested snps

### ISSUE THREAD

**Issue by FJ-H** [genetics-statistics/GEMMA#31]
Hi,
I'm wondering if there's a way to obtain the proportion of variance explained after adjustment on each snp in the GEMMA output after univariate LMM for marker association tests.
Indeed, I can find the PVE of the NULL model in the log.txt (I suppose that the fixed covariates independant of the betaX vector are included in the null model, but I'm not sure ),
and I can find the Lamba after adjustment for each snp tested, but this Lambda gives me the proportion of variance explained by the genetic relatedness matrix compared to the residual one, if I understood correctly. I haven't access to the "new" total variance with the marker as covariate, neither to the variance explained by the tested marker. Is there a way I haven't seen to compute it based on GEMMA outputs ?

Thank you !

**Comment by xiangzhou** [comment]
Yes, the software outputs the ratio between vg and ve for the alternative model (l_remle=vg/ve). Because vg+ve=1 (or the phenotype variance if the phenotype is not standardized) as SNP effect is always extremely small, you can get vg and ve for the alternative model back from l_remle.

**Comment by ColyFu** [comment]
@xiangzhou Sorry, I have read all topics, but I still have no idea about how to calculate pve by each single tested SNP.  While every SNP's l_remle were reported, is it right to calculate pve by (l_remle/(1+l_remle))?
