### ISSUE TITLE
Create R wrapper/interface for GEMMA

### ISSUE THREAD

**Issue by pcarbo** [genetics-statistics/GEMMA#35]
It would be preferrable if the R variables could be passed directly to GEMMA without having to save files.

Perhaps it could even be turned into a small R package (e.g., `rgemma`).

**Comment by timflutre** [comment]
+1 that would be great! maybe the first step to do is to refactor the core of the code into a stand-alone library, which would then be easy to call from R via Rcpp

**Comment by pjotrp** [comment]
I don't think GEMMA should be tied to R. We are using it from Python. You can still create an R wrapper that passes data in memory, but don't do away with the standard CLI. I would create a separate R package for this that may share the source code.

**Comment by timflutre** [comment]
Yes, I agree with @pjotrp, that's why I advocated for a library. In this way, the same library can be called by a simple .cpp file with a `main` function to be used from the CLI, but it can also be easily used by an R package via Rcpp, or from Python, or Julia, etc.

**Comment by pcarbo** [comment]
I agree @timflutre & @pjotrp.

**Comment by fboehm** [comment]
@timflutre From what I understand about libraries, I like the idea of creating a library, but I am new to C++. Can you say more about what we would need to do to create a library? How would we begin to refactor the core of the GEMMA code? Thanks!

**Comment by pcarbo** [comment]
@fboehm @timflutre It would involve replacing GEMMA's command-line interface, in which the data is read from files, with a single function that takes as input (1) the options, and (2) the data in the form of matrices (or perhaps data frames). The input could be passed from R to C++ via the [`.Call` interface in R](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#System-and-foreign-language-interfaces). However, I should warn you that designing this single function for interfacing the C++ code to R will be a substantial amount of work.

**Comment by timflutre** [comment]
@fboehm before refactoring anything, the first step is to automatize tests, as suggested in issue #38

**Comment by pjotrp** [comment]
We have tests. Closing this issue for now due to inactivity. Reopen if anyone wants to work on it.

**Comment by pjotrp** [comment]
Gemma2/lib is providing Python abstractions. An R wrapper may be part of that project.
