### ISSUE TITLE
size_t set to signed values

### ISSUE THREAD

**Issue by pcarbo** [genetics-statistics/GEMMA#37]
@xiangzhou According to [the C++ standard](https://stackoverflow.com/questions/1119370/where-do-i-find-the-definition-of-size-t), `size_t` is an unsigned integer type, but you are assigning (constant) negative values to variables of this type, which seems to be generating warnings in some cases; e.g., in `io.cpp`:

```C++
SNPINFO sInfo={"-9", rs, -9, -9, minor, major, -9, -9, (long int) -9};
```

So you should either replace these with unsigned values, or change the definition of `SNPINFO`.

**Comment by pjotrp** [comment]
I removed all compiler warnings in the latest build. Added only one cast in mvlmm.cpp.
