### ISSUE TITLE
Add test framework

### ISSUE THREAD

**Issue by pjotrp** [genetics-statistics/GEMMA#38]
It would be really nice to run the tests listed in the example directory. This would give some confidence that changes to the code base still deliver the same results.

**Comment by pcarbo** [comment]
I agree (and then we can add Continuous Integration as well). Do you have a good example of a repository with C/C++ code that does this? I am very familiar with implementing tests for R packages, but I've never done it for C/C++ code.

I've labeled this as an "enhancement", and I will address it as soon as I can.

**Comment by pjotrp** [comment]
Sambamba uses a very simple testing framework written in bash. It does not really matter what you select (for me). You can opt for R too. May work with your plans for creating a library. Guix has automatic CI, but it only works when a package gets updated. Travis CI is pretty flexible. Then gitlab also has a system...

**Comment by pcarbo** [comment]
@pjotrp Thansk for the suggestions.

**Comment by timflutre** [comment]
I agree with this very important recommendation. As an example of C++ package, I can suggest [eQtlBma](https://github.com/timflutre/eqtlbma) for which I am the maintainer. I implemented several functional tests (via bash and R), launched via `make check` (the package uses the Autotools). I never used continuous integration, but guess it shouldn't be too hard to do as long as `make check` works well.

**Comment by pjotrp** [comment]
Sambamba uses https://github.com/kward/shunit2/. It is just bash. E.g. https://github.com/lomereiter/sambamba/blob/master/.test_suite.sh. Would be easy to add the examples this way. Test for the return value or the return value of a diff on output (which is a regression test).

**Comment by pcarbo** [comment]
Thank you both for the suggestions.

**Comment by pjotrp** [comment]
Added test framework https://github.com/xiangzhou/GEMMA/pull/54
