### ISSUE TITLE
Do we need FORCE_FLOAT?

### ISSUE THREAD

**Issue by pcarbo** [genetics-statistics/GEMMA#39]
@xiangzhou I'm wondering if there is much benefit to including the `FORCE_FLOAT` option in GEMMA, which makes your code somewhat more complicated. You claim that this option is useful for reducing memory requirements, but have you tested this? Most computers (my guess is >99%) now have 64-bit architectures, which means that addressing is limited to 64 bits, which is the size of a double-precision floating-point number. In other words, a single-precision floating point number will also occupy 64 bits.

I can test this, but I'm quite certain that there will be no benefit to `FORCE_FLOAT` on a 64-bit architecture. If this is the case, perhaps we could consider removing this option from your code?

**Comment by xiangzhou** [comment]
The float version was mainly introduced for the bslmm model. I tried the float version a while ago on our previous cluster (pps cluster), and found that it only uses half the memory required by the double version (if I remember correctly, for 5k idv and 0.5million snps, the float version uses 8gb while the double version uses 16gb). But that was about 5 years ago. I am not sure either whether there is any benefit nowadays. It would be great if you could do a quick test on this, and we can certainly remove this option if there is no longer benefits.

**Comment by pcarbo** [comment]
@xiangzhou I will test to see if `FORCE_FLOAT` reduces memory usage in 64-bit systems.

**Comment by pjotrp** [comment]
Don't use float if you have double. You have to really know what you are doing.

https://wiki.haskell.org/Performance/Floating_point

**Comment by pcarbo** [comment]
@xiangzhou An update on this:

I wasn't able to build the binary executable using `FORCE_FLOAT = 1`; it generated several errors which did not seem straightforward to resolve.

Upon further experimentation in MATLAB, I think it is possible to reduce memory requirements with single-precision. I wasn't able to find any documentation about this in MATLAB, but [this webpage](https://docs.julialang.org/en/release-0.4/manual/integers-and-floating-point-numbers) briefly discusses storage of `<64-bit` numbers in Julia.

In short, there is a potential benefit to keeping the `FORCE_FLOAT` option. 

However, perhaps a larger issue is that debugging & maintaining single-precision and double-precision versions of GEMMA will involve more effort, and I'm not sure if the effort is justified by the benefit (which, in my opinion, is relatively small).

I've created a new branch [force-float](https://github.com/xiangzhou/GEMMA/tree/force-float) that preserves the state of the current repository with the `FORCE_FORCE` option, and my plan is to remove this option in the `master` branch unless there are any objections.

**Comment by pjotrp** [comment]
This is one of the best talks I ever heard. If you want to know about float/double, spend half an hour here. It is worth it. Entertaining too.

http://dconf.org/2016/talks/clugston

**Comment by tseemann** [comment]
I also had issues with `FORCE_FLOAT` in Linux.

**Comment by pcarbo** [comment]
@tseemann Thanks for sharing.
