### ISSUE TITLE
Add LOCO support for Plink format (Bimbam is in 0.97)

### ISSUE THREAD

**Issue by pjotrp** [genetics-statistics/GEMMA#46]
We should add leave one chromosome out support to GEMMA. From what I can tell from the source code this is not particularly hard because GEMMA already tracks chromosome information. We need to recompute the kinship matrix for n chromosomes leaving one out and then rerun the LMM and run GEMMA n+1 times and present a result file with n+1 scores. I think this should be an internal feature of GEMMA and one would like to save the precomputed kinship matrices for rerunning with covariates etc.

**Comment by pjotrp** [comment]
I am studying the GEMMA code to see how we add LOCO support.

**Comment by pcarbo** [comment]
Okay @pjotrp. It basically would involve an "outer loop" that would run relationship matrix creation + LMM association analysis on each chromosome. Note that I have [some R code](https://github.com/pcarbo/cfw/blob/master/R/gemma.R) that does this in case it is useful for helping to implement LOCO within gemma.

**Comment by pjotrp** [comment]
The outer loop may be the easiest hack for now though it will be hard to make generic for all supported input formats. If you look at the code you'll see that GEMMA has an innerloop for every file type it supports. I somehow need to plug in K-1 and subset SNPs. Looks like that will be pretty intrusive to make that generic.

**Comment by pjotrp** [comment]
I have implemented LOCO for Bimbam format. I'll put in a PR after we agree on the coding style, see https://github.com/genetics-statistics/GEMMA/pull/62

**Comment by xiangzhou** [comment]
I agree.

**Comment by pcarbo** [comment]
@pjotrp Sounds like a good plan to me!

**Comment by pjotrp** [comment]
https://github.com/genetics-statistics/gemma-wrapper now runs all chromosomes and caches results too. 

Leaving issue open until I add LOCO to Plink.

**Comment by pjotrp** [comment]
AnalyzeBimBam and AnalyzePlink contain duplicate logic - and they
differ now because the first has LOCO support. To add LOCO support to
PLINK we'll converge on logic and make the functions DRY.

The functions can be split into:

1. Initialization
2. Partially read genotype data (batch processing)
3. LMM on the submatrix
4. Collate the results
5. Cleanup

The only thing specific regarding the input file format is (2). The
way to solve is is to put that reader in a function that gets passed
in. I'll work on that in a new branch (for 0.98 release).

**Comment by pjotrp** [comment]
It will happen sometime this year. If you want to help out :). Meanwhile, convert plink to BIMBAM. It can be done with the plink tool.

**Comment by pjotrp** [comment]
It is part of gemma2/lib. Gemma2/lib converts plink and bimbam to a new Rqtl2/GEMMA2 format and that supports LOCO.
