### ISSUE TITLE
Odd sized kinship file

### ISSUE THREAD

**Issue by pjotrp** [genetics-statistics/GEMMA#55]
When running the new test testCenteredRelatednessMatrixK I get different resulting files on two build setups. One is the correct size, but the second has 1940 rows instead of 1410. The extra rows are the same as the tail of the previous - so, somehow, the output buffer gets overwritten. I'll scrutinize this more closely.

**Comment by pjotrp** [comment]
Oh yes, the other tools using K don's seem to mind. They don't read the full file. So, this may have been happening before, but it did not matter for the result.

**Comment by pcarbo** [comment]
@pjotrp Should I close this? It seems that it is not a bug after all?

**Comment by pjotrp** [comment]
No, I need to figure out what happened first.

**Comment by pjotrp** [comment]
Getting the same bug on my laptop. Test on master branch fails with
```
testCenteredRelatednessMatrixK
Reading Files ... 
## number of total individuals = 1940
## number of analyzed individuals = 1410
## number of covariates = 1
## number of phenotypes = 1
## number of total SNPs = 12226
## number of analyzed SNPs = 10768
Calculating Relatedness Matrix ... 
Reading SNPs  ==================================================100.00%
## total computation time = 0.35778 min 
ASSERT:expected:<24.9799> but was:<29.691>
```

and 

```
wc -l test/output/mouse_hs1940.cXX.txt 
1940 test/output/mouse_hs1940.cXX.txt
```

it appears it is outputting the number of individuals total, rather than the number used. @pcarbo what is the size of your output file?

**Comment by pcarbo** [comment]
@pjotrp I get an output file `mouse_hs1940.cXX.txt` with 1940 lines. I think the "number of aalyzed individuals" is misleading (and confusing!) because it is about the phenotype data, which is irrelevant for computing the relatedness matrix. If you look at the phenotype file you will see that there are 530 missing phenotype values:

```
$ cut -f 1 mouse_hs1940.pheno.txt | grep NA | wc -l
530
```

**Comment by pjotrp** [comment]
Cool, I swear I have seen a smaller K file. Anyway, we are getting different answers on different systems, so I am looking into that.

**Comment by pjotrp** [comment]
Turns out that the output files are identical, but that awk gives a different result on different machines! Not a gemma problem - I'll fix the test.

**Comment by pcarbo** [comment]
@pjotrp Interesting, thanks!
