### ISSUE TITLE
Association Tests with Univariate Linear Mixed Models using a non gemma index

### ISSUE THREAD

**Issue by dp0b** [genetics-statistics/GEMMA#59]
Hi 
 
I have been trying to run a univariate  linear mixed model. However I was hoping to use a grm I have made else where- it is the second in grm format. The  first few lines are as as follows

```
1       1       8.923316e-01
1       2       -5.544370e-02
1       3       1.903249e-02
1       4       1.880089e-02
1       5       9.801378e-02
1       6       -3.117359e-02
1       7       2.540684e-01
1       8       -1.174230e-01
1       9       1.168132e-01
1       10      1.833550e-01

```
Then I am trying to run a lmm using the follow command
`./gemma.linux -bfile mouse_hs1940 -km 2 -k mouse_plinkgctasorted.txt  -lmm 2 -o mouse_plinkgctasorted`

However I keep getting the following error. Any advice on how to fix this?
```
Reading Files ...
## number of total individuals = 1940
## number of analyzed individuals = 1410
## number of covariates = 1
## number of phenotypes = 1
## number of total SNPs = 12226
## number of analyzed SNPs = 10768
Start Eigen-Decomposition...
gsl: newton.c:74: ERROR: derivative is zero
Default GSL error handler invoked.
Aborted
```
The file will run the analysis when I supply a gemma grm, however the file I intend on supplying will be much larger and would prefer to make the grm elsewhere.

**Comment by pcarbo** [comment]
@dp0b Would it be possible to share the files you are using in the `gemma` command above so that I can reproduce your results? I will try to figure out why you are getting this error---if it is a bug in GEMMA, a data formatting problem, etc.

**Comment by dp0b** [comment]
Hi pcarbo,
Sorry for the delay.
Attached are the files, any info would be much appreciated. They are based on the example file












Hi Peter,
So the example is using is the mouse files you provide in the example when downloading the source code. I cant upload the grm in second format on this as its to large to upload on this. This was howver generated using plink and sorted to resemble the output in the manual of 
id1 id1
id1 id2
id1 id3
id2 id2
id2 id3

the following commands were used
```
plink --cow --bfile mouse _hs1940 --make-grm-gz no-gz --nonfounders --out mouse_plinkgcta
awk '{print $2,$1,$4}' mouse_plinkgcta.grm > temp.txt
sort -nk1 -nk2 temp.txt > mouse_plinkgctasorted.txt
./gemma.linux -bfile mouse_hs1940 -km 2 -k mouse_plinkgctasorted.txt  -lmm 2 -o mouse_plinkgctasorted
```
I hope that is of help. I do wonder is it something with line length as when I tried this with 100 samples from the mouse example it worked.

**Comment by pcarbo** [comment]
@dp0b I have not used the `-km 2` option before but my guess is that you have to give the sample ids in the first two columns, not the row indices of the samples. For example, the first line of the `mouse_plinkgctasorted.txt` file should be `A048005080 A048005080 8.923316e-01`. Can you try this and see if it works for you?

**Comment by dp0b** [comment]
Aghh yes, sorry about. Thank you very much for your help.

I was also wondering about the weights file? I have a weight calculated as effective record contribution (ERC) which ranges from 0.1 to 804. I have tested a few versions of including this as weight but would like your input as to what should be the correct version.  Does the weight value need to be less than one? I have tried including just the erc as is, a decimal of the erc-so divide by 1000, the reciprocal , and 1-ERC/1000. The latter seems to work best but if you have any information on how the residual weights should be construed it would be much appreciated.

Thanks for your help thus far.

**Comment by pcarbo** [comment]
@dp0b Are you referring to the `-widv` option in GEMMA?

**Comment by dp0b** [comment]
Sorry yes I am,if you have any information on the format they should be in it would be much appreciated

**Comment by xiangzhou** [comment]
The weight file contains a column of positive values to be used as weights for residuals. Every weight corresponds to an individual, and a high weight represents high residual error variance for this individual. The file is similar to the phenotype file with one phenotype or the covariate file with one covariate.

**Comment by pcarbo** [comment]
@xiangzhou I added this description to `gemma -h` and to the PDF manual in commit 3a06aee.

**Comment by pjotrp** [comment]
I think we can close this?
