### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by pcarbo** [genetics-statistics/GEMMA#64]
Hi @pjotrp, after your changes, I get the following error when running `make -f Makefile.linux` with g++ 4.8.5 and GSL 2.2.1 on RedHat Linux:

```
In file included from src/param.h:22:0,
                 from src/gemma.h:22,
                 from src/main.cpp:19:
src/debug.h:16:55: error: expected initializer before '__THROW'
                               const char *__function) __THROW
                                                       ^
make: *** [src/main.o] Error 1
```

**Comment by pcarbo** [comment]
I also get errors when running `make -f Makefile.macosx` on my MacBook Pro with g++ from Apple LLVM version 8.0.0 (clang-800.0.38). See the attached make output.

[make.out.gz](https://github.com/genetics-statistics/GEMMA/files/1205815/make.out.gz)

**Comment by pjotrp** [comment]
Yes, sorry. Remove the lines and insert include assert.h as I did in
https://github.com/genenetwork/GEMMA/commit/a97da56b1b964fbb0c64a97a6cdd7c05c63e5f3d. Would send you a patch, but I am remote and this is fastest.
