### ISSUE TITLE
Extracting the compiled version of GEMMA is not working

### ISSUE THREAD

**Issue by beausoleilmo** [genetics-statistics/GEMMA#65]
I've been trying to use the Mac OS X version of GEMMA, but it's not working. It won't extract the files. 

```
gunzip gemma.macosx.gz
> gunzip: gemma.macosx.gz: not in gzip format
```

Also, I've tried to compile GEMMA on macOS Sierra, but it's not working. 

```
g++ -Wall -Weffc++ -O3 -std=gnu++11 -m64 ./src/main.o ./src/param.o ./src/gemma.o ./src/io.o ./src/lm.o ./src/lmm.o ./src/vc.o ./src/mvlmm.o ./src/bslmm.o ./src/prdt.o ./src/mathfunc.o ./src/gzstream.o ./src/eigenlib.o ./src/ldr.o ./src/bslmmdap.o ./src/logistic.o ./src/varcov.o /usr/local/opt/gsl@1/lib/libgsl.a /usr/local/opt/gsl@1/lib/libgslcblas.a -lz -o ./bin/gemma
g++: error: /usr/local/opt/gsl@1/lib/libgsl.a: No such file or directory
g++: error: /usr/local/opt/gsl@1/lib/libgslcblas.a: No such file or directory
make: *** [bin/gemma] Error 1
```

**Comment by pcarbo** [comment]
@beausoleilmo It works for me. Did you download the binary from [the latest release](https://github.com/genetics-statistics/GEMMA/releases/tag/v0.96)?

We are working on improving the Makefile for building from source. You will need to edit `Makefile.macosx` and point to the GSL library installed on your computer. Note you need to use GSL 1.x; it is not compatible with GSL 2.x. One convenient approach is to install GSL 1.x using Homebrew.

**Comment by beausoleilmo** [comment]
OK! That works from this repository. Just letting you know that [on this page](http://www.xzlab.org/software.html) if you download the program, it's not working...
