### ISSUE TITLE
mvLMM and marginal pvalues

### ISSUE THREAD

**Issue by lfelipe-ferrao** [genetics-statistics/GEMMA#71]
Hello ,
I intend to use the mvLMM to find eventual positive pleiotropic effects in plants traits. GEMMA provides pvalues only for the so-called  "full test" (ie, it will test if the marker effect for the phenotype is different from zero). However, I also would like to get the marginal pvalues (in my notation, marginal pvalues means a hypothesis test for each phenotype, as if we are fitting a univariate model).  My guess is, if a SNP is significant for the mvLMM analysis and, at the same time, significant for two (or more) other traits I am looking at an eventual pleiotropic effect. 

 To get these marginal pvalues, should I use the univariate model (LMM) for each trait separately? If I understood correctly, this was the strategy used in the original paper by Zhou and Stephens, 2014 (Supplementary Table1), correct? 

Thank you,
Felipe

**Comment by xiangzhou** [comment]
Yes, you can use the univariate model to get these marginal pvalues. The univariate marginal pvalues are helpful to illustrate which trait(s) drives the multivariate signal, but they are not always consistent with multivariate p-values. For example, as we mentioned in the paper, it is possible that the multivariate p-value for two traits are significant, but the univariate p-values for either trait is not.
