### ISSUE TITLE
Relatedness matrix -n argument

### ISSUE THREAD

**Issue by boo62** [genetics-statistics/GEMMA#74]
I am confused about the -n argument when creating the relatedness matrix. This is supplied in line 117 in example/demo.txt to generate a relatedness matrix based on the training data. As the resulting matrix has values for all individuals, not just those with missing values, I was wondering what difference the argument makes to the calculations.

**Comment by pcarbo** [comment]
@boo62 If you try with `-n 1` and `-n 2` you will get slightly different relatedness matrices. I agree it is unclear why this is happening; intuitively the relatedness matrix should be the same regardless of the choice of phenotype used, but I will forward this question to Xiang.

**Comment by xiangzhou** [comment]
Different -n option will determine how many samples/individuals are used to compute maf, which is used further to determine which set of SNPs are used for the computation of K. For example, -n 1 option may use 1000 individuals to compute maf, while -n 2 option may use only 100 individuals to compute maf. Therefore, the two different options will lead to slightly different K matrices.

**Comment by pcarbo** [comment]
Thanks @xiangzhou. @boo62 Is that explanation clear to you?

**Comment by boo62** [comment]
Yes, that's cleared things up. Thanks.
