### ISSUE TITLE
Add MacOSX build environment to Travis CI

### ISSUE THREAD

**Issue by pcarbo** [genetics-statistics/GEMMA#75]
You can add osx in the matrix, e.g., [here](https://github.com/jenkinsci/ansicolor-plugin/pull/60/files). In fact, you can automatically generate a latest-release by pushing to
dropbox (or something) [as Artem did](https://github.com/lomereiter/sambamba/blob/master/.travis.yml).

*Note:* Currently the compiler options in the Makefile do not appear to be compatible with the XCode version of gcc (e.g., Apple LLVM version 8.1.0) so this will have to be addressed as well.

**Comment by pjotrp** [comment]
Done.
