### ISSUE TITLE
GSL ERROR: matrix is singular in lu.c at line 266 errno 1

### ISSUE THREAD

**Issue by pjotrp** [genetics-statistics/GEMMA#78]
Two covariates an older gemma with GSL1 gives NaN output and the new GSL shows above error. Looking into it...

**Comment by pjotrp** [comment]
Turns out the covariates were highly correlated. With GSL1 no error was reported. GSL2 does the right thing.

**Comment by pcarbo** [comment]
@pjotrp Yes, that's exactly what you want---a point to GSL 2.x.

**Comment by pjotrp** [comment]
Maybe we should report the GSL version at runtime (I now do it at build time)

**Comment by pcarbo** [comment]
@pjotrp I fully support that idea. Hopefully there is a GSL function that will provide this info?

**Comment by pjotrp** [comment]
Done in https://github.com/genetics-statistics/GEMMA/pull/83. Also added Eigen version.

**Comment by pcarbo** [comment]
@pjotrp Great!
