### ISSUE TITLE
gsl: init_source.c:29: ERROR: matrix dimension n1 must be positive integer

### ISSUE THREAD

**Issue by roslen** [genetics-statistics/GEMMA#80]
Error from a basic call as shown below. The bfile was used previously in emmax and gcta without issues.
gemma -bfile <bfile_prefix> -gk 1 -o <test_output>

**Comment by roslen** [comment]
I should have read the manual first. Sorry guys. This is not a gemma issue. :)

**Comment by pcarbo** [comment]
@roslen Thanks for letting us know! And please tell us if the manual wasn't clear.
