### ISSUE TITLE
Why not printing out beta and se(beta) under -lmm 2?

### ISSUE THREAD

**Issue by wanyuac** [genetics-statistics/GEMMA#81]
Hello,

GEMMA (v0.96 and earlier versions) does not print the MLE of beta and its standard error when the likelihood-ratio test is used (-lmm 2), whereas it does print the REMLE of beta and se when the Wald test is used.

Column names under -lmm 1
chr	rs	ps	n_miss	allele1	allele0	af	beta	se	l_remle	p_wald

Column names under -lmm2
chr	rs	ps	n_miss	allele1	allele0	af	l_mle	p_lrt

May I have any reasons for this difference? It would be convenient for users to have beta and its s.e. printed under the second mode to assess the direction of association.

In addition, would it be possible to print the log likelihood under the alternative hypothesis (logl_H1), or can we have an option to turn it on? According to GEMMA's codes, it is actually calculated but is not printed (lmm.cpp, line 120, and variable "double logl_H1 = 0.0"). However, it may be useful for evaluating the goodness of fit. In fact, authors of the BUGWAS package have modified GEMMA to print out this value. It may be helpful to users if the standard release of GEMMA prints this value as well.

Thanks.

**Comment by pcarbo** [comment]
@pjotrp @xiangzhou These seem like reasonable requests. Is there any particular reason GEMMA is not outputting these columns, or is this an oversight?

**Comment by xiangzhou** [comment]
This is indeed an oversight. It would be useful to output these.

**Comment by wanyuac** [comment]
Many thanks for your replies.

**Comment by pcarbo** [comment]
@pjotrp I've labeled this as an "enhancement" to be incorporated at some point into a new release, whenever you have a chance to get to it.

**Comment by Owen-haha** [comment]
When running GEMMA with `-lmm 4`, there is only one beta, but two lambda values (`l_remle` and `l_mle`). Is this beta estimated by remle or mle? I  cannot find hint in the manual.

**Comment by xiangzhou** [comment]
> When running GEMMA with -lmm 4, there is only one beta, but two lambda values (l_remle and l_mle). Is this beta estimated by remle or mle? I cannot find hint in the manual.

The beta is estimated from remle. In fact, no beta is computed when performing likelihood ratio test.

**Comment by pjotrp** [comment]
Should be fixed now with https://github.com/genetics-statistics/GEMMA/pull/92. Also logl_H1 output added. Please test.

**Comment by pjotrp** [comment]
In the release notes we should state that the output has changed.

**Comment by pjotrp** [comment]
With a PR merge and confirmation this works we can do the 0.97 release.

**Comment by pcarbo** [comment]
@pjotrp With `-lmm 2`, I now see `logl_H1` and the standard error (se), but no beta estimate column. Should there be one?

**Comment by pjotrp** [comment]
beta should not be seen for LRT according to @xiangzhou's comment above. So I wrote https://github.com/genetics-statistics/GEMMA/commit/86323ccaf26ad0a3b706a67a0014dd04b9965823#diff-f9c43469f48c6abce4b57e1fdd4c329aR110

**Comment by pjotrp** [comment]
In fact, for lmm2 we should also not display se!

**Comment by pcarbo** [comment]
@pjotrp In principle one should be able to compute the mean and s.e. of beta if the likelihood is being computed, but doing this will involve a little bit more work, so perhaps we could postpone fixing this issue for now.

**Comment by pjotrp** [comment]
See https://github.com/genetics-statistics/GEMMA/issues/90

**Comment by Noemi-Nicole** [comment]
> @pjotrp In principle one should be able to compute the mean and s.e. of beta if the likelihood is being computed, but doing this will involve a little bit more work, so perhaps we could postpone fixing this issue for now.

Hi all,
Regarding this issue, I would like to ask you: Can you help me to find out how I can retrieve beta and its se from **logl_H1** obtained by **-lmm2** ? (if you have papers or documentation would be great).

I am a research student, so pretty new in the field, but I would like to understand it in the proper way. 
Many thanks !

**Comment by xiangzhou** [comment]
You will need to use -lmm 1 or -lmm 3 to retrieve beta and its se. -lmm 2 does not output beta estimates, since it performs a likelihood ratio test.

**Comment by Noemi-Nicole** [comment]
Thank you, I replied to you (with two further questions) on the google group.

Best,
Noemi
