### ISSUE TITLE
Please help me with a problem(Illegal instruction)

### ISSUE THREAD

**Issue by DongHyeok-Micro** [genetics-statistics/GEMMA#82]
I want to run GEMMA but i get the following error with example file
<Reading Files ... 
Illegal instruction>

I am not familiar with Linux and can not find a solution on Google.
What do i do with that problem?

Thank you in advance for your reply.

**Comment by pjotrp** [comment]
Can you give the full command and the full output that you get?

**Comment by pcarbo** [comment]
@DongHyeok-Micro Also, please tell us what version of GEMMA you downloaded, and what operating system you are using.

**Comment by DongHyeok-Micro** [comment]
I tried running the program through another server and it worked fine.
Maybe it was a version issue.
GEMMA 0.96
openSUSE 12.2 "Mantis"
Linux version 3.4.6-2.10-desktop
(These are the versions, right?)
