### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by prasunanand** [genetics-statistics/GEMMA#84]
`make -j8` leads to an error
```
prasun@ubuntudev:~/dev/genenetwork/GEMMA$ make -j8
g++ -g -O3  -std=gnu++11 -isystem//usr/include/eigen3 -Icontrib/catch-1.9.7 -Isrc  -c src/gemma.cpp -o src/gemma.o
g++ -g -O3  -std=gnu++11 -isystem//usr/include/eigen3 -Icontrib/catch-1.9.7 -Isrc  -c src/vc.cpp -o src/vc.o
g++ -g -O3  -std=gnu++11 -isystem//usr/include/eigen3 -Icontrib/catch-1.9.7 -Isrc  -c src/logistic.cpp -o src/logistic.o
g++ -g -O3  -std=gnu++11 -isystem//usr/include/eigen3 -Icontrib/catch-1.9.7 -Isrc  -c src/mvlmm.cpp -o src/mvlmm.o
g++ -g -O3  -std=gnu++11 -isystem//usr/include/eigen3 -Icontrib/catch-1.9.7 -Isrc  -c src/lapack.cpp -o src/lapack.o
g++ -g -O3  -std=gnu++11 -isystem//usr/include/eigen3 -Icontrib/catch-1.9.7 -Isrc  -c src/prdt.cpp -o src/prdt.o
g++ -g -O3  -std=gnu++11 -isystem//usr/include/eigen3 -Icontrib/catch-1.9.7 -Isrc  -c src/mathfunc.cpp -o src/mathfunc.o
g++ -g -O3  -std=gnu++11 -isystem//usr/include/eigen3 -Icontrib/catch-1.9.7 -Isrc  -c src/lmm.cpp -o src/lmm.o
g++ -g -O3  -std=gnu++11 -isystem//usr/include/eigen3 -Icontrib/catch-1.9.7 -Isrc  -c src/bslmm.cpp -o src/bslmm.o
src/mathfunc.cpp: In function ‘bool isMatrixPositiveDefinite(const gsl_matrix*)’:
src/mathfunc.cpp:233:42: error: ‘gsl_linalg_cholesky_decomp1’ was not declared in this scope
   auto s = gsl_linalg_cholesky_decomp1(G2);
                                          ^
Makefile:130: recipe for target 'src/mathfunc.o' failed
make: *** [src/mathfunc.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by pcarbo** [comment]
@prasunanand It looks like you are using Ubuntu? Have you installed GSL 1.x or GSL 2.x? Do you know where GSL is installed on your computer?

@pjotrp It doesn't look like we have variables in the Makefile specifically for the location of the GSL library and include files. What Makefile variable do you recommend setting for this when the include & library files are in a nonstandard location?

**Comment by pjotrp** [comment]
I link against non-standard libgsl to test versions. There is an example of use in: https://github.com/genenetwork/GEMMA/blob/master/INSTALL.md

**Comment by pjotrp** [comment]
You can add overriding variables, but I prefer to keep it simple and stick to the common case. And we have a way to set the include search path and library loads.

**Comment by pcarbo** [comment]
@pjotrp I'm looking at this command:

```
make EIGEN_INCLUDE_PATH=~/.guix-profile/include/eigen3 WITH_OPENBLAS=1 GCC_FLAGS="-Wall" LIBS="$HOME/opt/gsl1/lib/libgsl.a $HOME/opt/gsl1/lib/libgslcblas.a -L$HOME/.guix-profile/lib -pthread -llapack -lblas -lz"
```

How does it work without adding `-I$HOME/opt/gsl1/include` in `GCC_FLAGS`? This is normally what I would do.

**Comment by pjotrp** [comment]
Default behaviour of the Makefile should just pick up what is on the system. If you need to override include files or libraries (something that is *not* common), simply use above command. @prasunanand GSL is standard in Linux distributions and should work out of the box. Look at the .travis script to see how it is done. https://github.com/genetics-statistics/GEMMA/blob/master/.travis.yml

**Comment by prasunanand** [comment]
@pcarbo I have `GSL2.1` on my machine.

```
$ whereis gsl
gsl: /usr/include/gsl /usr/share/man/man3/gsl.3.gz
```
@pjotrp I followed the .travis script. I reinstalled everything and yet the same error.

**Comment by prasunanand** [comment]
I found the issue .
`gsl_linalg_cholesky_decomp1` has been introduced in GSL 2.3.
The current code expects it  to be introduced in GSL 2.0.

http://git.savannah.gnu.org/cgit/gsl.git

I am submitting a patch.

**Comment by pcarbo** [comment]
Wonderful @prasunanand! That is very helpful.

**Comment by pjotrp** [comment]
Good. Check for the minor GSL version too.

**Comment by prasunanand** [comment]
Yeah, I am doing that.
```
#if GSL_MAJOR_VERSION >= 2
    #if GSL_MINOR_VERSION >= 3
      auto s = gsl_linalg_cholesky_decomp1(G2);
    #else
      auto s = gsl_linalg_cholesky_decomp(G2);
    #endif
  #else
    auto s = gsl_linalg_cholesky_decomp(G2);
  #endif
```

**Comment by pjotrp** [comment]
Do not nest if statements. This is ugly.
