### ISSUE TITLE
Improve instructions for using & adapting Makefile 

### ISSUE THREAD

**Issue by pcarbo** [genetics-statistics/GEMMA#87]
Provide more guidance for compiling GEMMA on Mac and Linux. Instructions could be added as comments in the `Makefile` and/or included in INSTALL.md. Most importantly, it isn't clear which variables should be modified to specify the locations of the GSL & BLAS libraries and include files.

**Comment by pjotrp** [comment]
I think it is clear from the Makefile and INSTALL doc. At least for Linux.
