### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by skoyama427** [genetics-statistics/GEMMA#88]
I download and try to use precompiled version of gemma(linux). But it did not work(core dump)

```
./gemma.linux -bfile GEMMA-0.96/example/mouse_hs1940 -bslmm 1 -o output
Reading Files ...
## number of total individuals = 1940
## number of analyzed individuals = 1410
## number of covariates = 1
## number of phenotypes = 1
## number of total SNPs = 12226
## number of analyzed SNPs = 10768
Start Eigen-Decomposition...
Illegal instruction (core dumped)
```

And I am now trying to compile by myself. 
But I got such errors.

```
src/param.cpp:1059:94: error: ‘gsl_matrix_const_subrow’ was not declared in this scope
        gsl_vector_const_view KiKl_row=gsl_matrix_const_subrow (KiKj, k, t_il*ni_test, ni_test);
                                                                                              ^
src/param.cpp:1104:94: error: ‘gsl_matrix_const_subrow’ was not declared in this scope
        gsl_vector_const_view KiKl_row=gsl_matrix_const_subrow (KiKj, k, t_il*ni_test, ni_test);
                                                                                              ^
src/param.cpp:1122:94: error: ‘gsl_matrix_const_subrow’ was not declared in this scope
        gsl_vector_const_view KjKm_row=gsl_matrix_const_subrow (KiKj, k, t_jm*ni_test, ni_test);
                                                                                              ^
Makefile:108: recipe for target 'src/param.o' failed
make: *** [src/param.o] Error 1
```

How does it work ? I use libgsl2.1, should I replace it?

Many thanks.

**Comment by pcarbo** [comment]
@skoyama427 First of all, could you tell us more about using the precompiled version of GEMMA? Were you able to get other GEMMA commands in the mouse demo to work successfully (e.g., `-lmm`)?

For compiling GEMMA, it sounds like your installation of GSL may be in a non-standard location, and gcc can't find the include and/or library files. Do you know where the GSL include files (e.g., `gsl_vector.h`) are located?

**Comment by pcarbo** [comment]
@skoyama427 Actually, my mistake… I think the issue is that you need to install `GSL >= 2.3`. Please see Issue #84.

**Comment by skoyama427** [comment]
Thanks, pcarbo

I updated to gsl 2.4 then compile was completed, however I found error below

`
./gemma: error while loading shared libraries: libgsl.so.23: cannot open shared object file: No such file or directory
`

And also I tried precompiled gemma again, I can execute -lm option however, when I tried -lmm option after the calculation of relatedness-matrix, I encountered the error below

`
../gemma.linux -bfile mouse_hs1940 -lmm 1 -k output/mouse_relate.cXX.txt -o output/mouse_lmm
Reading Files ... 
`
`
number of total individuals = 1940  
`
`
number of analyzed individuals = 1410  
`
`
number of covariates = 1  
`
`
number of phenotypes = 1  
`
`
number of total SNPs = 12226  
`
`
number of analyzed SNPs = 10768  
`
`
Start Eigen-Decomposition...  
`
`
zsh: illegal hardware instruction (core dumped)  ../gemma.linux -bfile mouse_hs1940 -lmm 1 -k output/mouse_relate.cXX.txt -o  
`

**Comment by pcarbo** [comment]
@skoyama427 Okay, you have made some progress. One possibility is that you need to set `LD_LIBRARY_PATH` so that your shell environment knows where to find the GSL library. See for example [here](https://stackoverflow.com/questions/13428910/how-to-set-the-environmental-variable-ld-library-path-in-linux).

**Comment by skoyama427** [comment]
Finally I could exec gemma with your help.
Match thanks!

**Comment by pjotrp** [comment]
LD_LIBRARY_PATH should not be used, e.g., http://xahlee.info/UnixResource_dir/_/ldpath.html. 

You do not need that. Better specify the LIBS as shown in https://github.com/genetics-statistics/GEMMA/blob/master/INSTALL.md#install-from-source
