### ISSUE TITLE
I can't start the gemma software

### ISSUE THREAD

**Issue by white002** [genetics-statistics/GEMMA#89]
when I used the command './gemma.linux', it showed me an error : '' error while loading shared  libraries : libgfortran.so.3: cannot open shared object file: no such file or directory''
how can i fixed this problem ?

**Comment by pcarbo** [comment]
@white002 Can you tell us a little more about your setup? (operating system, version of gcc you have, etc) It looks like either you do not have gfortran installed, or it is in a non-standard location on your computer, and therefore GEMMA is unable to find it. (I noticed that we failed to mention that gfortran is used to build the software; we should add this info somewhere.)

**Comment by white002** [comment]
I only download the gemma software version 0.96 and open it.
I think I don't have gfortran installed, where can I install the gfortran?
thank you for your answer.
