### ISSUE TITLE
Permutation with GEMMA

### ISSUE THREAD

**Issue by hxtao** [genetics-statistics/GEMMA#93]
Hi 👍 
 When I was working on GWAS, I had trouble using GEMMA software.For the results of the GEMMA software,i want to use permutation method to correct my GWAS results.
 Permutation method, I usually  keep the genotype of the individual will remain unchanged, individual phenotypes within groups randomly swap 10000 times, each time to compute a p value (ten thousand), and then select all the minimum p value, an empirical distribution (in ascending order), the construction of 5% p value as a correction value P, the original value is less than the value of P is significant experience. 
So i used plink to generate permuted phenotype filesets.
code like this  ./plink  --bfile txt --make-perm-pheno 10000 -out txt 
But i have no idea how to use this permuted phenotypes to perform in GEMMA for GWAS .

**Comment by pcarbo** [comment]
@hxtao Please see [this R script](https://github.com/pcarbo/cfw/blob/master/R/map.qtls.gemma.R) for an example of implementing a permutation test using GEMMA. There is no built-in function in GEMMA to do this.

Note that permuting the phenotypes while keeping the genotypes fixed is technically not valid when there is populations structure / unequal relatedness in your data set. See [this paper](http://dx.doi.org/10.1534/genetics.114.167056) for a discussion of this point in the Methods section, and see [Mark Abney's paper](http://home.uchicago.edu/~abney/abney_web/Publications_files/abney2015a.pdf) for a more thorough investigation of this.

**Comment by hxtao** [comment]
Hi Peter;

First of all,Thanks for your reply.I have seen the R script.I have some details to ask.

When we use R to perform permutation, we should load gemma.exe format:  system(paste(gemma.exe .But I haven't found the exe format.Besides I have no idea about this step: rows<- sample(nrow(pheno)).





 

-----原始邮件-----
发件人:"Peter Carbonetto" <notifications@github.com>
发送时间:2017-10-08 04:42:25 (星期日)
收件人: genetics-statistics/GEMMA <GEMMA@noreply.github.com>
抄送: hxtao <hxtao@cau.edu.cn>, Mention <mention@noreply.github.com>
主题: Re: [genetics-statistics/GEMMA] Permutation with GEMMA (#93)



@hxtao Please see this R script for an example of implementing a permutation test using GEMMA. There is no built-in function in GEMMA to do this.

Note that permuting the phenotypes while keeping the genotypes fixed is technically not valid when there is populations structure / unequal relatedness in your data set. See this paper for a discussion of this point in the Methods section, and see Mark Abney's paper for a more thorough investigation of this.

**Comment by pcarbo** [comment]
@hxtao That line of code will generate a permutation of the numbers from 1 to n, where n is the number of rows of the `pheno` data frame. I recommend that you download the CFW data set and walk through the steps of the R script so that you can understand what it is doing. Instructions for downloading the data (from Data Dryad) are provided in that Github repo.

**Comment by pjotrp** [comment]
Please continue on the mailing list https://groups.google.com/forum/#!forum/gemma-discussion

**Comment by pcarbo** [comment]
@hxtao We are migrating all Q&A and discussion (except for bug reports and development-related discussion) to the GEMMA mailing list. If you have any followup questions, I encourage you to subscribe to the mailing list and post your questions there. Please see:

https://groups.google.com/group/gemma-discussion

(Note it is easy to unsubcribe at any point.)
