### ISSUE TITLE
How to open the gemma software

### ISSUE THREAD

**Issue by white002** [genetics-statistics/GEMMA#95]
hi, I have a question when I opened the gemma software in linux, 
I have an error told the <error while loading shared libraries : libgfortran.so.3: cannot open shared object file: no such file or directory>
Please tell me how to fix it, thank you

**Comment by pcarbo** [comment]
@white002 You posted Issue #89 twelve days ago, and you did not respond to our questions. Is this the same error, or a different one?

**Comment by white002** [comment]
I'm so sorry, I can't found my question, so I posted it again. 
I will read the last question answer, thank you for your remind.

**Comment by white002** [comment]
I only download the gemma software version 0.96 and open it.
I think I don't have gfortran installed, where can I install the gfortran?
I download the GSL libraries but it does't work?
Is that right to download the GSL libraries first?
thank you for your answer.

**Comment by white002** [comment]
@pcarbo 
Thank you for your answer,
I can use the software when I download the gfortran, 
very thank your for your answer.
